### ISSUE TITLE
Adding support for Outline VPN

### ISSUE THREAD

**Issue by ibnesayeed** [dlenski/openconnect#100]
Google's Jigsaw recently [introduced Outline](https://medium.com/jigsaw/introducing-outline-making-it-safer-to-break-the-news-feda4d047b4), a self-hosted VPN system. Their server runs on Linux inside a Docker container, but they currently have no [clients for Linux](https://github.com/Jigsaw-Code/outline-client/issues/10). I was wondering is it possible to add support for it in a generic VPN client like OpenConnect?

**Comment by dlenski** [comment]
>  I was wondering is it possible to add support for it in a generic VPN client like OpenConnect?

This looks like an interesting project. Though I'm wondering why Google/Alphabet decided to develop a new VPN from scratch given that a very good and easy-to-install open-source VPN _server_ already exists in the form of [ocserv](//ocserv.gitlab.io/www)… and `ocserv` has the great advantage of supporting the already-existing `openconnect` clients _and_ it also tries to support the Cisco AnyConnect client.

Anyway… it'd probably be possible to support in OpenConnect, and easier than other protocols given that it's open-source.

However:

1. I can't find a technical description of how the outline protocol works. What authentication methods does it support? Is it purely HTTPS/TLS-based, or does it use a more efficient UDP transport too (ESP/DTLS)? Does it exchange authentication data in some format that openconnect already supports (HTTP headers, XML) or something new like Protocol Buffers or JSON?
2. _This specific project_ is focused on supporting the PAN GlobalProtect VPN protocol in `openconnect`.

I'd be interested in working on supporting more protocols in openconnect, but not sure when I'd have time. It might be worthwhile to post on the [official openconnect mailing list](http://www.infradead.org/openconnect/mail.html) **with more technical details**, to see if anyone else is enthusiastic about supporting Outline.

**Comment by dlenski** [comment]
Ideally openconnect would support _every VPN under the sun_ because it has a good internal design and is very flexible in terms of routing configuration.

But that ain't gonna happen without someone doing a lot of work. And since outline already has good open-source clients, it has less need than other VPNs (*cough* check-point mobile *cough*)

Closing.
