### ISSUE TITLE
CSD/TNCC/HIP scripts on Windows

### ISSUE THREAD

**Issue by jmichler** [dlenski/openconnect#106]
Hi,

Obviously today there is no way to habe HIP scripts on the windows builds of OpenVPN / Globa protect . I'm not sure to be honest I'd this is the right place here or if I should send an email to mailto:openconnect-devel@lists.infradead.org.

To be honest I didn't understand the post on the openconnect windows gui for 100% were I was referred to here and to infradead itself.

**Comment by jmichler** [comment]
what I ment was: Is this something to be developed/discussed in in openconnect "core" (http://www.infradead.org/openconnect/mail.html) or since it is windows related in this repository? I just wanted to make sure that this is not again in the wrong place.

**Comment by dlenski** [comment]
There is nothing Windows-specific in _this_ repository… are you thinking of https://github.com/openconnect/openconnect-gui, which is the home of the GUI client for windows?

**Comment by jmichler** [comment]
Hi, well in the openconnect-gui I was told that this is not GUI-related. Then I'll  bring the idea to the infraded-repository itself, shouldn't I? Or is it "globalprotect-specific" and belongs into your copy of the project?

**Comment by dlenski** [comment]
> Hi, well in the openconnect-gui I was told that this is not GUI-related.

Right. The lack of support for CSD/TNCC/HIP on Windows is a limitation of the "base" openconnect, not the GUI.

> Then I'll bring the idea to the infraded-repository itself, shouldn't I?  Or is it "globalprotect-specific" and belongs into your copy of the project?

Well… it's complicated.

Every supported protocol will need a slightly different solution to support running the security script (AnyConnect→CSD, Juniper→TNCC, GlobalProtect→HIP).

_Specifically_ for GlobalProtect+HIP: this **is** the place for it. However: **I** don't use Windows very much, **I** don't know enough about process control on Windows, and **I** don't have time to learn. So if you want HIP support in Windows, someone else is going to need to write it.

Pull requests welcome :sunglasses:

**Comment by jmichler** [comment]
Hi,

thanks, that clarifies matters. But then still I think implementing it for GlobalProect->HIP would be way easier if that would be there already for AnyConnect->CSD, wouldn't it? And such a Script makes sense for AnyConnect->CSD as well. And since this is the source I'll suggest it for AnyConnect->CSD first. I'm not a C Windows/LInux-Prorammer unfortunately, so I doubt I can provide that pull request, sorry.

**Comment by dlenski** [comment]
> I think implementing it for GlobalProect->HIP would be way easier if that would be there already for AnyConnect->CSD, wouldn't it? 

Maybe. Implementing GlobalProtect HIP on Windows requires being able to run a script (similar to the `vpnc-script`) whereas implementing AnyConnect CSD on Windows requires being able to run a server-provided "black box"/trojan binary that has to be invoked in a very strange way…

Unfortunately they'll probably require separate implementation because of this :(

> I'm not a C Windows/LInux-Prorammer unfortunately, so I doubt I can provide that pull request, sorry.

Anyone willing to implement support on Windows is more than welcome to do so, and I'll provide whatever documentation I can… but I have neither the time nor the enthusiasm to learn to program on Windows myself.

**Comment by dlenski** [comment]
Closing and locking this issue. See upstream https://gitlab.com/openconnect/openconnect/-/issues/53 if you're interested in this topic.
