### ISSUE TITLE
--passwd-on-stdin breaks smartcard PIN input

### ISSUE THREAD

**Issue by 01000101** [dlenski/openconnect#107]
# Problem description

When using a smartcard (via PKCS#11) with the `--passwd-on-stdin` flag, the smartcard's PIN prompt does not stay available for user input but instead immediately errors with `fgets (stdin): Inappropriate ioctl for device`. 

An unsuccessful run (does not allow me to enter a PIN) looks like this - 
```
# echo "MY-PASSWORD" | /usr/local/sbin/openconnect --protocol="gp" --pfs --os="linux-64" --no-proxy --no-dtls -c "pkcs11:model=ID%20Prime%20MD;manufacturer=Gemalto;serial=XXXXXXXXXXXX;token=Gemalto%20IDPrime%20830%20B%20%2b%20Mifare%204;id=%XX%XX%XX%XX%XX%XX%XX%XX;object=te-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx;type=cert" --user="jcornutt" --passwd-on-stdin 11.22.33.44

Please enter your username and password
POST https://11.22.33.44/ssl-vpn/login.esp
Connected to 11.22.33.44:443
PIN required for Gemalto IDPrime 830 B + Mifare 4
Enter PIN:
fgets (stdin): Inappropriate ioctl for device
```

If I remove the piped in password and the `--passwd-on-stdin` flag, I get prompted for both my user password as well as my PIN and can successfully connect. 

# Operating system and openconnect-gp version

openconnect-gp version (built less than an hour ago):

```
OpenConnect version v7.08-298-gf5094628
Using GnuTLS. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp
```

operating system

```
Linux xxxxxxxx 4.16.5-200.fc27.x86_64 #1 SMP Fri Apr 27 19:05:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dlenski** [comment]
See my comments on #103.

**Comment by 01000101** [comment]
@dlenski Great, thanks! I was able to solve my use case with the third variant (adding in the `-s` flag to `read` to not display the PIN).

**Comment by kecinzer** [comment]
May I ask for little help here.
I'm solving similar issue, that I need to wait for SMS code. I'm able to put SMS response, but then I get error:
Wait for token to change,
then enter the new tokencode:
Response:
fgets (stdin): Inappropriate ioctl for device

My script looks like this:
(echo -e "pass1\npass2"; read -s) | sudo openconnect --user=username vpn.company.org/adm

**Comment by dlenski** [comment]
> My script looks like this:
>
> ```
> (echo -e "pass1\npass2"; read -s) | sudo openconnect --user=username vpn.company.org/adm
> ```

Why do you think this should work? `read -s` just reads a line from `stdin` and then _discards it_ without piping it to openconnect.

**Comment by Vozf** [comment]
For anyone wondering how to make this work with 2 factor authentication with google authenticator you can do this 
Use this to create 2 factor codes on your pc https://github.com/arcanericky/ga-cmd
Store your account password  in `.cisco/pass.txt`
Then use this to use vpn 
```
echo -e "$(sudo cat ~/.cisco/pass.txt)\n$(ga-cmd <your-ga-site-name>)" | sudo openconnect --user=<username> --passwd-on-stdin <your-vpn.com>
```
