### ISSUE TITLE
ansible role to idempotently install

### ISSUE THREAD

**Issue by senorsmile** [dlenski/openconnect#108]
Thanks a million for this work!  It is working perfectly for me. 

I have created an ansible role that installs this idempotently on Ubuntu (tested on 16.04). 

I'm not sure the best way to share; hence this ticket: 
https://github.com/senorsmile/ansible-role-openconnect-globalprotect

**Comment by dlenski** [comment]
Thanks, this is great to hear. I don't use `ansible` but happy to see you're using it. It looks like the ansible build config file is quite similar to `.travis-ci.yml`… cool!
