### ISSUE TITLE
Commands and DNS server

### ISSUE THREAD

**Issue by murphycc** [dlenski/openconnect#11]
Dan,

Great work, as I've been wanting to get GlobalProtect working with Linux for a long time now.

One point during installation I noticed, is that some people might need to use the following to copy your github repository instead of what you typed:

git clone git://github.com/dlenski/openconnect

I also needed to 'sudo' the './configure' command prior to making the program, otherwise it won't find the vpnc script.

Finally, I found that my dns servers are not updated once I connect. I have to use an actual IP address to connect. Actually, tonight, I could not connect to local external sites when I had VPN connected. Have you had any problems with this? My resolv.conf file only points to 127.0.1.1. Not sure how to specify the tunneling of this for local and remote site names.

Thanks,
Chris

**Comment by dlenski** [comment]
> git clone git://github.com/dlenski/openconnect

I'm not sure why you would _need_ to use a different form of the remote, unless you're behind a firewall that only allows HTTP(S). I'll change it in the readme to make it a bit more foolproof.

> I also needed to 'sudo' the './configure' command prior to making the program, otherwise it won't find the vpnc script.

This doesn't have anything to do with this version in particular. You should not have to run it as root. You should read the allowed arguments (`./configure --help`) and then specify the correct vpnc-script with `--with-vpnc-script`.

> Finally, I found that my dns servers are not updated once I connect. I have to use an actual IP address to connect. Actually, tonight, I could not connect to local external sites when I had VPN connected. Have you had any problems with this?

OpenConnect (including this version) takes whatever DNS settings it receives from the VPN gateway, and passes them to the `vpnc-script`. I haven't had any problems passing the correct DNS servers to the `vpnc-script`.

Please connect to your VPN with `openconnect --dump` and extract the [getconfig response](https://gist.github.com/dlenski/5046e5f934ac111e8d8718fc10c25703#response-2) and post it here. You can replace any domain names you don't want to show publicly with a placeholder. It's possible that your VPN uses a slightly different format for the DNS servers than what OpenConnect-GP expects.

**Comment by murphycc** [comment]
I think I need to create a hosts file or otherwise dictate which hostnames use which DNS server (i.e. create a split tunnel).

Does your vpn-slice script work with this fork of openconnect you made? I installed vpn-slice through pip3 but it somehow can't find the script when I use the -s 'vpn-slice ...' command in conjunction with openconnect.

Thanks...

**Comment by dlenski** [comment]
Yep, I wrote `vpn-slice` specifically to work with openconnect and they work together perfectly for me. 

This fork exports DNS servers and routing information in exactly the same format as the official open connect does for Cisco AnyConnect VPNs… so they should work together correctly unless openconnect isn't reading the routing information from your VPN correctly. Which is why I asked about the format and contents of the getconfig XML.

**Comment by dlenski** [comment]
@murphycc, any luck fixing the DNS resolution issue? Can I close this issue?

**Comment by murphycc** [comment]
Hi Dan,

I haven't had time to anonymize the transcript from using openconnect yet. Unless there's a certain portion you're interested in that would show what it's doing with DNS servers and/or hosts.

I got the vpn-slice installed last night. You might want to notate on vpn-slice and this openconnect which commands require 'sudo' to run. I only mention this because I initially installed vpn-slice using your instructions with pip3, and it didn't complain and appeared to work, but it could not find the executable, nor could I manually (even in /usr/local/bin instead of /usr/bin). Turns out I realized if I was expecting an executable in that directory I should run it with sudo, which it then created in /usr/local/bin. Usually it's obvious with commands, but with pip3 it doesn't complain.

Anyhow, I so I got vpn-slice installed last night but haven't tried it yet with your openconnect fork.

So to answer your question, you may close this issue unless you know specifically what you're looking for (i.e. section) in the anonymous log transcript you want me to capture. That would help me.

Thanks,
Chris

**Comment by dlenski** [comment]
> I got the vpn-slice installed last night. You might want to notate on vpn-slice and this openconnect which commands require 'sudo' to run. I only mention this because I initially installed vpn-slice using your instructions with pip3, and it didn't complain and appeared to work, but it could not find the executable, nor could I manually (even in /usr/local/bin instead of /usr/bin).

`pip3` can install packages both in users' home directories (`pip3 --user`) as well as system-wide. Some people might want to install `vpn-slice` in their home directories. On Ubuntu systems, at least, `pip3` puts user-local executables in `~/.local/bin`.

> I haven't had time to anonymize the transcript from using openconnect yet. Unless there's a certain portion you're interested in that would show what it's doing with DNS servers and/or hosts.

These are the main parts of the GlobalProtect getconfig that I'm interested in: DNS servers and access routes.

```
  <dns>
    <member>8.8.8.8</member>
    <member>4.4.4.4</member>
  </dns>
  <access-routes>
    <member>10.0.0.0/8</member>
    <member>192.168.0.0/16</member>
  </access-routes>
```

Those are the only parts that could potentially affect the accessibility of DNS servers when connected to the VPN. OpenConnect simply takes the DNS servers sent by the VPN, and passes them to the vpnc-script.

Once you are connected to the VPN, take one of the DNS servers sent by the VPN and try looking up a hostname on it, e.g. `nslookup DNS.server.IP.address www.google.com`.

Without more information, I can't make any progress on this issue.

**Comment by murphycc** [comment]
Dan,

I did get vpn-slice working with openconnect, and local and remote IP addresses work now.

For DNS and access route sections of the openconnect dump, I have truncated some addresses and included info below. I will note that the DNS section contains only internal servers on the remote side (10.#.#.#)... no public DNS server there. I tried changing mine on my local machine to google's (8.8.8.8 by changing resolv.conf) with no change in this DNS section. My original one was 127.0.0.1 I think.

I tried the nslookup thing and looking up google.com on the different DNS addresses would just hang and not connect.

My local router assigns IP addresses 192.168.#.# if that's helpful.

Chris

 		<dns>
< 			<member>10.a.b.c</member>
< 			<member>10.x.y.z</member>
< 		</dns> 

		<access-routes>
(3 more unique 10.#.#.# addresses)
(1 192.#.#.# address)
(5 more unique 10.#.#.# addresses)
< 			<member>10.a.b.c/32</member>
< 			<member>10.x.y.z/32</member>
< 		</access-routes>

**Comment by dlenski** [comment]
Well... It seems like everything is behaving as expected. Your VPN's DNS servers *don't* allow you to lookup external hosts, although they also don't include the default route (`0.0.0.0/32`) so nothing prevents you from routing traffic to external hosts identified by their  IP addresses. 

So when you connect using the "normal" `vpnc-script `, you can't access any external hosts by name.

OpenConnect is behaving as expected here.

If you access this VPN from the Windows or MacOS official GP clients... is anything different?

**Comment by dlenski** [comment]
(Also, obfuscating addresses in the 10.* and 192.168.* ranges isn't necessary, because they are in the [private IP blocks](https://en.m.wikipedia.org/wiki/Private_network) and can't be used to identify a computer from outside the network in question.)

**Comment by murphycc** [comment]
Could it be there are different vpnc-scripts I should use? I copied the main one from the openconnect github, since I thought it odd a vpnc-script was not installed when I installed vpnc.

Official GP client works fine from Windows. URL name lookups work fine for external or internal addresses.  Although it usually takes 10-15 seconds for internal domain names to resolve when using Windows and official GP client (I only connect to two URLs), so who knows how many DNS servers Windows is searching, or if it would have same problem as openconnect on Linux but tries other default DNS servers. Using openconnect with your vpn-slice on Linux right now enables DNS resolution to internal names in < 1 second.

Not sure if the GP client does something different in all this.

I purposely wanted to obfuscate the internal IP addresses too.

**Comment by dlenski** [comment]
> Official GP client works fine from Windows. URL name lookups work fine for external or internal addresses.

Please run this under Windows:

```cmd
C:\> ipconfig /all | findstr /R "DNS\ Servers"
```

Does it show the **same** two DNS servers that are in the getconfig XML? Or does it show different ones?

> Not sure if the GP client does something different in all this.

The GP client receives the same XML configuration file that OpenConnect receives, and the standard `vpnc-script` handles the configuration in a very similar way to what GlobalProtect does (it sets the routes that go through the VPN, sets the DNS servers based on the ones provided by the VPN).

**Comment by murphycc** [comment]
When I did what you asked about the nslookup the other night, it would hang indefinitely. Turns out the format is actually flipped and should be: nslookup domain dns-server, so I actually was able to get responses from nslookup (e.g. www.google.com) using the two internal IPs (10.a.b.c, 10.x.y.z) when connected through OC VPN.

Anyhow, I connected to VPN again just now, and external addresses DID work, but names for the internal again did NOT work. Then, after literally a few minutes, external addresses would no longer work, and the internal addresses (by URL) would still not work. While external addresses ARE working, a nslookup www.google.com shows it's using my 127.0.1.1 DNS. When external addresses are NOT working nslookup www.google.com (w/o specifying DNS) hangs. It still works if I do nslookup through the 10.a.b.c/10.x.y.z DNS.

Throughout this time the openconnect dump log is spewing out 'Send ESP probes for DPD' every few seconds, and when I ctrl-c openconnect, I have to hit ctrl-c twice instead of once, and afterwards it says 'Failed to reconnect to host XYZ: Interrupted system call'. It will exit gracefully just hitting ctrl-c once if I do it before the external URLs no longer work. I can exit gracefully even after a few of the "...DPD" messages appear, but apparently something happens if too many appear because then it will exit ungracefully.

I also looked at DNS addresses using Windows 10 GP client:

Windows:
(no VPN) 192.168.1.1
(with GP VPN client) 10.a.b.c, 192.168.1.1

Linux:
(no VPN) 127.0.1.1
(with OC VPN) 10.a.b.c, 10.x.y.z

So there is the additional DNS server added when connected to VPN. Is my local DNS address (for my computer) supposed to appears in the DNS field of openconnect dump log also?

So something is changing after a few minutes, which might be related to why the "...DPD" logs are coming out?

Chris

**Comment by dlenski** [comment]
Aha, very useful findings! I think there are actually two different problems going on here…

> Throughout this time the openconnect dump log is spewing out 'Send ESP probes for DPD' every few seconds, and when I ctrl-c openconnect, I have to hit ctrl-c twice instead of once, and afterwards it says 'Failed to reconnect to host XYZ: Interrupted system call'. It will exit gracefully just hitting ctrl-c once if I do it before the external URLs no longer work. I can exit gracefully even after a few of the "...DPD" messages appear, but apparently something happens if too many appear because then it will exit ungracefully.

Hmm... it seems that something is making the ESP-over-UDP connection unreliable. This could be a misconfiguration of the GP VPN server (I've seen several cases of this) or perhaps a misconfigured firewall or proxy in between your computer and the server.

Try `openconnect --no-dtls` (should really be called `--no-udp`). This will force OpenConnect to use SSL/HTTPS _only_, with no UDP. The performance of the tunnel connection over SSL is not as good, but it is more reliable since even really screwed up routers and firewalls will let HTTPS traffic through.

>I also looked at DNS addresses using Windows 10 GP client:
>
>Windows:
>(no VPN) 192.168.1.1
>(with GP VPN client) 10.a.b.c, 192.168.1.1
>
>Linux:
>(no VPN) 127.0.1.1
>(with OC VPN) 10.a.b.c, 10.x.y.z
>
>So there is the additional DNS server added when connected to VPN. Is my local DNS address (for my computer) supposed to appears in the DNS field of openconnect dump log also?

Also quite interesting. It appears that under Windows, the VPN DNS servers are _added_ to the pre-existing list of DNS servers, rather than _replacing_ them.

Probably there is an option in the getconfig XML response to trigger this behavior in the GlobalProtect client, but I haven't seen it if so. What does your getconfig show for this field?

```xml
  <no-direct-access-to-local-network>no</no-direct-access-to-local-network>
```

**Comment by murphycc** [comment]
I tried the --no-dtls option and pretty much the same thing happens where it takes a minute or so before external URLs do not work. Internal ones never work.

I did the logging and could not see a <no-direct-access-to-...> field anywhere. I looked at the examples and it's supposed to be somewhere between dns and access routes fields.

It seems to me it's related to the vpnc-script, since internal/external work perfectly (and no problems after a few minutes) when using openconnect with your vpn-slice script, which I understand substitutes for the vpnc-script.

**Comment by dlenski** [comment]
> It seems to me it's related to the vpnc-script, since internal/external work perfectly (and no problems after a few minutes) when using openconnect with your vpn-slice script, which I understand substitutes for the vpnc-script.

Okay, well if you're happy with how it's working with `vpn-slice` then that's good.

As for what's going wrong after a few minutes with the default `vpnc-script`…

I have a theory that the routing table for your VPN includes a route for the *external* IP address of the VPN gateway. Is that so? Is the *external* IP address of the gateway in one of the subnets in `<access-routes>`?

If it is, then the `vpnc-script` will reconfigure the routing table so that traffic *to the VPN gateway*… is supposed to go through the VPN. That will break the connection to the gateway whenever the kernel decides to refresh its mapping of IP addresses to network interface, which is perhaps after a few minutes.

If my (potentially crazy) theory is correct, then it's a misconfiguration of the VPN, and it's a good reason to be using `vpn-slice` rather than trusting the configuration that it sends out.

**Comment by murphycc** [comment]
Under the <access-routes> section of log, there are (9) 10.#.#.# addresses (so all internal), plus my own 192.168.1.0, which I don't think exists because my router is 192.168.1.1. I think modem is a different IP. When I connect to VPN also, I cannot connect to 192.168.1.1 which is my router. Should that be the case?

**Comment by dlenski** [comment]
Okay, now I got it. Your access route contains something like `192.168.0.0/16`, doesn't it?

```xml
  <access-routes>
    <!-- this would mean "route all traffic to `192.168.*.*`" through the VPN -->
    <member>192.168.0.0/16</member>
  </access-routes>
```

If that's the case…

* The default `vpnc-script` would dutifully follow this instruction.
* … which would interfer with your connection to your own router (`192.168.1.1`) which is your computer's connection to the outside world
* … which would screw pretty much everything else up
* … which is why you just can't trust the routing configurations sent by corporate VPNs not to screw everything up. :rage:
* … which is why it's a good idea to use `vpn-slice` with dirty, intrusive, misconfigured corporate VPNs.

**Comment by murphycc** [comment]
Right, well, the access route contains 192.168.1.0/24, which I can never access even without VPN. So I think what you say makes perfect sense.

I would have to change my router IP address probably to 192.168.1.0, but not worth doing.

Thanks for all the help. I'll continue using vpn-slice with it.

**Comment by dlenski** [comment]
Yep, that'll do it. It's not very nice of the corporate VPN to use anything in `192.168.0.0/16` as a subnet, since these addresses are so commonly used by home routers :-1:.

It might be worth submitting a patch on `vpnc-script` to make it check for this case and not clobber the route to the default gateway.
