### ISSUE TITLE
aclocal for autogen

### ISSUE THREAD

**Issue by goodpunk6** [dlenski/openconnect#111]
my problem is in building this thing but it is not covered in the link you provided. when i run autogen, i get the error aclocal not found. what can i do to resolve?

**Comment by dlenski** [comment]
* What OS, distribution?
* Do you have this problem building the upstream openconnect? (Assuming yes, maybe ask or check on the [upstream mailing list](http://www.infradead.org/openconnect/mail.html).)

**Comment by goodpunk6** [comment]
ubuntu 16.04.
i have this problem when i run autogen.sh upon initial install

**Comment by dlenski** [comment]
Closing due to insufficient information.
