### ISSUE TITLE
The config parameter "key-password" seems not working 

### ISSUE THREAD

**Issue by wade0817wang** [dlenski/openconnect#112]
hi  dlenski,

I have successfully built and run openconnect. 
But now I want to run it in the backgroud with config "alias conn="nohup sudo openconnect --user=user --key-password=pwd --protocol=gp vpn.server.com > /dev/null 2>&1 &".  But it failed. It seems like the key-password not working. Any suggestions?

Hope for your reply, thx.

**Comment by wade0817wang** [comment]
thanks for your reply. 
It's my fault. I misunderstood this parameter. But how can i config my ldap accout with simple user/pwd ? Any other parameter?

**Comment by dlenski** [comment]
> how can i config my ldap accout with simple user/pwd ? Any other parameter?

What do you mean? Are you asking, "how can I make a script automatically enter my regular account password?"

```
echo password | sudo openconnect --user=user --passwd-on-stdin --protocol=gp vpn.server.com
```

**Comment by wade0817wang** [comment]
yes， thanks

**Comment by dlenski** [comment]
This option is explained in the openconnect manual: http://www.infradead.org/openconnect/manual.html#heading4

Passing the password on the command line could be a security hazard because the arguments of all processes are normally visible to all users.
