### ISSUE TITLE
XML reponse has no "auth" node

### ISSUE THREAD

**Issue by varshaneya** [dlenski/openconnect#114]
I'm trying to connect to a VPN gateway x.x.x.x using openconnect in ubuntu. When I use GUI for openconnect I'm getting the error "Server 'x.x.x.x' requested Basic authentication which is disabled by default. XML reponse has no "auth" node".
So I switched to CLI and ran sudo openconnect -v x.x.x.x. I got the error "Failed to obtain WebVPN cookie".
I have credentials to connect to use that VPN.

I'm using Ubuntu 16.04 with Openconnect v7.06 downloaded using apt. I'm connecting to CISCO VPN.

Why is this error occuring and what could be the solution?
Thanks in advance.

**Comment by dlenski** [comment]
`--protocol=gp`

**Comment by varshaneya** [comment]
I did that. I'm getting a new error as "openconnect: unrecognized option '--protocol=gp'".

**Comment by dlenski** [comment]
You're running a version of openconnect other than this one, lacking global protect support.

**Comment by dlenski** [comment]
There's a reason that the Github issue template asked you to give the complete output of `openconnect --version `.

**Comment by dlenski** [comment]
Ah, hold on. You're running an *official* open connect build (v7.06) and trying to connect to a *Cisco* gateway…

First off, you're submitting this issue on a repository for a fork that adds support for the GlobalProtect protocol.

But secondly, forget the first bit. You should include the detailed debug log of `openconnect -vvvv --dump`, as specified in the issue template.

**Comment by imrank0** [comment]
hello, has there been any resolution to this case ?
apologies that I am commenting to a closed -issue.. i tried finding much but so far nothing worked and so far I found no solution.
using ubuntu 16.04, and getting below:
XML response has no "auth" node
Failed to obtain WebVPN cookie

**Comment by dlenski** [comment]
@imrank0, start a new issue and provide more information.
