### ISSUE TITLE
GP: username and passwrod are still asked with cert/key in use

### ISSUE THREAD

**Issue by gaydenko** [dlenski/openconnect#117]
Hi! For GP I use `-c` and `-k` options (and that `pem`s are used/tested on anyconnect connection) to authenticate, but username and password are still asked. Why?

**Comment by dlenski** [comment]
What is the _problem_ here? Are you saying that your GlobalProtect VPN doesn't need you to enter a username/password at all to login, *just* a certificate?

**Comment by gaydenko** [comment]
From you question I can guess user/password are obligatory for GP.
Just can not connect with openconnect
```
Authentication failure: Invalid username or password
Failed to obtain WebVPN cookie
```
, while do can with globalprotect official client, but have got hang with the last, and this is another story :)

**Comment by dlenski** [comment]
> From you question I can guess user/password are obligatory for GP.

I don't **know** if they are obligatory. I have never seen a GlobalProtect VPN that _doesn't_ require a username/password, but that doesn't mean they don't exist.

I need more information here.

If you think this applies to your VPN, then please pull the pre-login configurations from your VPN host, and post as much of them as you can:

```sh
curl -A 'PAN GlobalProtect' 'https://SERVER/global-protect/prelogin.esp
curl -A 'PAN GlobalProtect' 'https://SERVER/ssl-vpn/prelogin.esp
```

> Just can not connect with openconnect

Please fill out the information requested in the template. What OS are you using? What version of openconnect?

**Comment by gaydenko** [comment]
I can not share all details, but you have helped me already, thanks! - the first request explicitly says username and password are expected (as well as client certificate). But the second one says "gateway does not exist" - not sure what does it mean.

**Comment by dlenski** [comment]
> the first request explicitly says username and password are expected (as well as client certificate). 

You should be able to obfuscate any confidential parts (username, password, server names).

The first one is something like this, I presume…? **Is there anything significant besides what I'm showing here?**

```xml
<prelogin-response>
<status>Success</status>
<ccusername/>
<autosubmit>false</autosubmit>
<msg/>
<newmsg/>
<authentication-message>Enter login credentials</authentication-message>
<username-label>Username</username-label>
<password-label>Password</password-label>
<panos-version>1</panos-version>
<region>US</region>
</prelogin-response>
```

And the second one must be something like this…

```xml
<prelogin-response>
<status>Error</status>
<ccusername/>
<autosubmit/>
<msg>GlobalProtect gateway does not exist</msg>
<newmsg/>
<license>yes</license>
<authentication-message/>
<username-label/>
<password-label/>
<panos-version>1</panos-version>
<region/>
</prelogin-response>
```

The fact that your GlobalProtect server is "portal only" means that you should connect with a command line like this, in order to skip attempting a connection to the nonexistent gateway interface:

```openconnect -c CERT.pem -k KEY.pem --usergroup=portal --protocol=gp SERVER```

**Comment by gaydenko** [comment]
Sincere thanks! 
'usergroup' option was that little detail which has resolved my problem!

**Comment by dlenski** [comment]
> 'usergroup' option was that little detail which has resolved my problem!

That's extremely strange. It is supposed to autodetect the case where the server is portal only.

Please tell me what version of openconnect-gp you are running (`openconnect --version`).

**Comment by gaydenko** [comment]
OpenConnect version v7.08-128-g5eabc1af , that is (may be almost)  the current master tip, I guess.
