### ISSUE TITLE
Structuring GlobalProtect/Okta/SAML Authentication Flow

### ISSUE THREAD

**Issue by aclindsa** [dlenski/openconnect#122]
I've been playing around with openconnect and my VPN, and have managed to get it working by studying how my existing client works with mitmproxy, hacking up [gp-okta.py](https://github.com/arthepsy/pan-globalprotect-okta) from @arthepsy, and using it together with your [test-globalprotect-login.py](https://github.com/dlenski/openconnect/blob/globalprotect/test-globalprotect-login.py).

I *think* that my authentication flow is different from others', and want to a) confirm that is true and b) see what the best way to handle these differences are. To start, here are the URLs in my flow:

1.  https://vpn.example.com/global-protect/prelogin.esp
2.  https://example.okta.com/app/panw_globalprotect/abcdefg1234567ABCDEF/sso/saml
3.  https://example.okta.com/api/v1/authn
4.  https://example.okta.com/login/sessionCookieRedirect
5.  https://vpn.example.com/SAML20/SP/ACS
6.  https://vpn.example.com/global-protect/getconfig.esp
7.  https://vpn.example.com/ssl-vpn/prelogin.esp
8.  https://example.okta.com/app/panw_globalprotect/abcdefg1234567ABCDEF/sso/saml
9.  https://vpn.example.com/SAML20/SP/ACS
10. https://vpn.example.com/ssl-vpn/login.esp
11. https://vpn.example.com/ssl-vpn/getconfig.esp

I think the thing that differs here from how gp-okta.py currently handles it is that my ssl-vpn/prelogin.esp (7 above) redirects me back into the Okta authentication loop, where I end up getting a second prelogin-cookie, which is then what I ultimately present to ssl-vpn/login.esp in request 10 above.

In order to get this all to work, I modified gp-okta.py to handle 7-9 in addition to the 1-6 @arthespy's code already handles (my modifications: https://github.com/arthepsy/pan-globalprotect-okta/pull/7). I then pull the `prelogin-cookie` I get from 9, pass that to `test-globalprotect-login.py` for 10, and finally pass the `authcookie` from that into my openconnect command-line (11). This looks something like:

```
# ./gp-okta.py gp-okta.conf
# export PRELOGIN_COOKIE="XXX"
# ./test-globalprotect-login.py \
    -u aclindsa@example.com \
    https://vpn.example.com/ssl-vpn/login.esp \
    prelogin-cookie=$PRELOGIN_COOKIE
# export AUTH_COOKIE="XXX"
# sudo openconnect \
    --protocol=gp \
    --usergroup=gateway \
    vpn.example.com \
    --cookie "authcookie=${AUTH_COOKIE}&portal=EXAMPLE-GP-GATEWAY-N&user=aclindsa%40example.com&domain=%28empty_domain%29&computer=hostname&preferred-ip="
```
I think there's a possibility this is similar to some of the work you all are already doing, but I so far haven't been able to figure out anything existing that fits my VPN. I apologize if I've duplicated work already being done and will gladly take suggestions for better ways to structure this or other patches to test.

**Comment by dlenski** [comment]
This is very useful. Since I don't have access to any VPN that uses SAML myself, I've been a bit in the dark about how the whole thing works.

Few questions…

> I *think* that my authentication flow is different from others', and want to a) confirm that is true and b) see what the best way to handle these differences are. To start, here are the URLs in my flow:
> 
> 1.  https://vpn.example.com/global-protect/prelogin.esp

This uses the usual `<saml-auth-method>REDIRECT</saml-auth-method><saml-request>base64-encoded-url</saml-request>`…

> 2.  https://example.okta.com/app/panw_globalprotect/abcdefg1234567ABCDEF/sso/saml
> 3.  https://example.okta.com/api/v1/authn
> 4.  https://example.okta.com/login/sessionCookieRedirect
> 5.  https://vpn.example.com/SAML20/SP/ACS

Which "cookies" are involved in steps 2-5? If I'm reading https://github.com/arthepsy/pan-globalprotect-okta/pull/7 correctly, you receive (a) a `prelogin-cookie` and then (b) a `portal-userauthcookie`…

> 6.  https://vpn.example.com/global-protect/getconfig.esp

And then in (6) you *use* the `prelogin-cookie` in place of the normal `passwd` to fetch the portal config…

> 7.  https://vpn.example.com/ssl-vpn/prelogin.esp

Same as (1).

> 8.  https://example.okta.com/app/panw_globalprotect/abcdefg1234567ABCDEF/sso/saml
> 9.  https://vpn.example.com/SAML20/SP/ACS

And then in the second SAML dance you get… a _new and different_ `prelogin-cookie`? Or the _same_ one?

> 10. https://vpn.example.com/ssl-vpn/login.esp

And then finally you use the `prelogin-cookie` in place of the normal `passwd` (you _don't_ need `test-globalprotect-login.py` for this; `echo $COOKIE | openconnect --prot=gp --usergroup gateway:prelogin-cookie` should handle it fine.)

Do I have all that about right? What I don't fully understand is if and why the portal login is absolutely necessary, or if you can skip it and go directly to the gateway login. (Probably the answers are yes and "it's messy.")

**Comment by dlenski** [comment]
Bottom line: there _seem to be_ a ton of variants of how the SAML authentication flow works with GlobalProtect (even just restricting to Okta).

But I still believe it should be possible to write "one script to rule them all" that will:
    1. Start by pulling `/global-protect/prelogin.esp`
    2. Pop up a browser to let the user login
    3. Use something like [`browsercookie`](https://pypi.org/project/browsercookie/) to detect when the required cookies have been generated.
    4. Pipe those back into `/SAML20/SP/ACS` (or `/global-protect/getconfig.esp` or `/ssl-vpn/login.esp`… or whatever the web page says is "next."
    5. Finally output the required connection information in the [shell-variable format produced by `openconnect --authenticate`](http://www.infradead.org/openconnect/manual.html#SIGNALS).

… all of which will allow the user to just do:

```sh
$ eval $( one-globalprotect-saml-script-to-rule-them-all gpvpn.company.com )
$ echo "$COOKIE" | openconnect --servercert="$FINGERPRINT" --prot=gp "$HOST"
```

**Comment by dlenski** [comment]
> I've got <saml-auth-method>POST</saml-auth-method> and it looks like the SAML encodes an HTML form that gp-okta.py is pulling the URL out of, but essentially yes.

Huh, I hadn't seen that one, only `REDIRECT` from an example posted by another user. That seems to be a key difference.

What does the SAML request form contain?

**Comment by dlenski** [comment]
Closing this because it's being hashed out more productively over at https://github.com/arthepsy/pan-globalprotect-okta/pull/7 …

For the time being, OpenConnect itself can't do much more other than tell the user when it runs into a portal that wants to use SAML auth, which is what v8.x does.

**Comment by aclindsa** [comment]
@dlenski Sorry, I just realized I never answered your question about `<saml-auth-method>POST</saml-auth-method>`. I don't know if you still care, but for me, the base64-decoded contents of `<saml-request>` look like:

```
<html>
<body>
<form id="myform" method="POST" action="https://example.okta.com/app/panw_globalprotect/abcdefg1234567ABCDEF/sso/saml">
<input type="hidden" name="SAMLRequest" value="LONG_BASE64_THING" />
<input type="hidden" name="RelayState" value="SHORT_BASE64_THING" />
</form>
<script>
  document.getElementById('myform').submit();
</script>
</body>
</html>
```
Where SHORT_BASE64_THING looks like garbage when base64 decoded (a 40-byte ID or key of some sort, maybe?), and LONG_BASE64_THING looks like:
```
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="https://vpn.example.com:443/SAML20/SP/ACS" Destination="https://example.okta.com/app/panw_globalprotect/abcdefg1234567ABCDEF/sso/saml" ID="_24d25faf937c82b4f05c5327a0f9da53" IssueInstant="2018-09-10T14:35:23Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://vpn.example.com:443/SAML20/SP</saml:Issuer></samlp:AuthnRequest>
```
