### ISSUE TITLE
HTTP traffic works SSH doesn't

### ISSUE THREAD

**Issue by epronk** [dlenski/openconnect#123]
OS: Ubuntu 18.04

I can connect and browse via HTTP, but connecting to remote servers via SSH gets stuck.

Update: I can get SSH to work with "ssh -c aes256-ctr ". Could be MTU related.
(see https://serverfault.com/questions/210408/ssh-access-problem-debug1-expecting-ssh2-msg-kex-dh-gex-reply)

There is something wrong with my HTTP traffic as well. Leaving comments in Jira fails which suggests that an HTTP POST can arrive corrupted at the server end.

The only odd thing I see in the logs is:
> Accepting later-than-expected ESP packet with seq 1 (expected 0)

> Gateway says no HIP report submission is needed.
> Parameters for incoming ESP: SPI 0x641e1b41
> ESP encryption type AES-128-CBC (RFC3602) key 0xe1424834ec29005521aceef18e61a346
> ESP authentication type HMAC-SHA-1-96 (RFC2404) key 0x70079911950d1e9f1aec5c41d5f65219e8482721
> Parameters for outgoing ESP: SPI 0x5debd8da
> ESP encryption type AES-128-CBC (RFC3602) key 0x8cd6c609c6d3fd1bb6fcfb326d6a55d0
> ESP authentication type HMAC-SHA-1-96 (RFC2404) key 0x4124a4481b679ac4c2ab22bb2154b801c878c012
> Send ESP probes
> Connected as 192.168.33.70, using SSL, with ESP in progress
> Received ESP packet of 84 bytes
> Accepting later-than-expected ESP packet with seq 1 (expected 0)
> ESP session established with server
> Received ESP packet of 84 bytes
> Accepting expected ESP packet with seq 2
> Received ESP packet of 84 bytes
> Accepting expected ESP packet with seq 3
> ESP tunnel connected; exiting HTTPS mainloop.
> Sent ESP packet of 100 bytes
> No work to do; sleeping for 10000 ms...
> Sent ESP packet of 116 bytes
> No work to do; sleeping for 10000 ms...
> Sent ESP packet of 132 bytes
> No work to do; sleeping for 10000 ms...
> Received ESP packet of 212 bytes
>

**Comment by dlenski** [comment]
Please include exact version and OS as specified in the issue template.

If you suspect it's an MTU-related issue, use `-m SmallerValueThanWhatOCGuesses` to reduce it.

**Comment by epronk** [comment]
OS: Ubuntu 18.04

Thanks. I wasn't aware of the `-m` option. 
I used `sudo ifconfig wlp2s0 mtu 1200` which works.
> wlp2s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1200
> tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1214

I'll leave the MTU of my network interface untouched (defaults to 1500) and will try some different values using the `-m` options.

**Comment by dlenski** [comment]
What version **of openconnect** are you running?

**Comment by epronk** [comment]
> OpenConnect version v7.08-334-g2d2da477

The next tests I did without specifying `-m`.

When my interface MTU is 1500 I get:

> TCP_INFO rcv mss 1418, snd mss 1418, adv mss 1460, pmtu 1500
> No MTU received. Calculated 1422 for ESP tunnel

ifconfig reports:
> tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1410

Any value greater than 1430 give fragmentation.

> ping -M do -s 1430 vpn.mycompany.com

I need to modify my system in order for openconnect to work.

> ifconfig wlp2s0 mtu 1430

When my MTU = 1430 I get:

> TCP_INFO rcv mss 1390, snd mss 1390, adv mss 1390, pmtu 1430
> No MTU received. Calculated 1358 for ESP tunnel

ifconfig reports the same:
> tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1410

When I add `-m 1358` the `tun0` gets configured accordingly:

> tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1358

(It is probably a good idea for me to set the MTU to 1430 permanent for my system. I haven't found a way to do this in Ubuntu yet which now has netplan but wifi is managed by NetworkManager.)

This is workable for now. If this is stable I'm actually very happy with this fork. Thank you!

**Comment by dlenski** [comment]
Thanks. So `-m 1358` is the _largest_ value you can specify and have a fully functional connection? How did you arrive at this value?

Do you get the same maximum functional MTU if you specify `--no-dtls` on the command line? (Makes it TCP only, no UDP.)

**Comment by epronk** [comment]
I got to `-m 1358` using the following steps:
> sudo ifconfig wlp2s0 mtu 1500

binary search got me to 1430.

> $ ping -M do -s 1430 8.8.8.8
> PING 8.8.8.8 (8.8.8.8) 1430(1458) bytes of data.
> 1438 bytes from 8.8.8.8: icmp_seq=1 ttl=120 time=57.6 ms

1431 gives "Message too long".

> $ ping -M do -s 1431 8.8.8.8
> PING 8.8.8.8 (8.8.8.8) 1431(1459) bytes of data.
> ping: local error: Message too long, mtu=1458

I configure the interface to use MTU = 1430:

> sudo ifconfig wlp2s0 mtu 1430

Now openconnect without specifying `-m` calculates 1358. 
> TCP_INFO rcv mss 1390, snd mss 1390, adv mss 1390, pmtu 1430
> No MTU received. Calculated 1358 for ESP tunnel

After that I added `-m 1358` to my `/etc/systemd/system/openconnect.service`.

I'll try `--no-dtls` for a few hours tomorrow and let you know how that goes.

**Comment by dlenski** [comment]
Ah, I see. So the MTU of your underlying WiFi network device was configured to be too large, causing OC to calculate an overly-optimistic MTU for the tunnel as well.

I'm sort of surprised that "everything else" wasn't broken with the underlying MTU set too large. Perhaps OpenConnect needs to implement a binary search for the optimal MTU … :-/

**Comment by dlenski** [comment]
Closing since this version is obsolete and OpenConnect v8.x+ has substantially improved MTU detection across protocols.
