### ISSUE TITLE
OS spoofing breaks GP authentication (for me, at least)

### ISSUE THREAD

**Issue by baergj** [dlenski/openconnect#126]
5da09b13acbd6f668094d17b8a05c7685d748bae breaks authentication against my company's VPN when running from linux-64. I receive the following:
```
Got HTTP response: HTTP/1.1 512 Custom error
Date: Tue, 02 Oct 2018 15:38:07 GMT
Content-Type: text/html
Content-Length: 127
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
x-private-pan-sslvpn: auth-failed
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-FRAME-OPTIONS: DENY
HTTP body length:  (127)
< 
< var respStatus = "Error";
< var respMsg = "Authentication failed: Invalid username or password";
< thisForm.inputStr.value = "";
< 
Unexpected 512 result from server
Invalid username or password.
```
Simply doing the following allows things to work again:
```diff
diff --git a/auth-globalprotect.c b/auth-globalprotect.c
index 5b2d3ec1..f1d364b5 100644
--- a/auth-globalprotect.c
+++ b/auth-globalprotect.c
@@ -362,8 +362,8 @@ static int gpst_login(struct openconnect_info *vpninfo, int portal, char *pw_or_
 
                /* submit gateway login (ssl-vpn/login.esp) or portal config (global-protect/getconfig.esp) request */
                buf_truncate(request_body);
-               buf_append(request_body, "jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:&clientos=Windows");
-               append_opt(request_body, "os-version", vpninfo->platname);
+               buf_append(request_body, "jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:");
+               append_opt(request_body, "clientos", vpninfo->platname);
                append_opt(request_body, "server", vpninfo->hostname);
                append_opt(request_body, "computer", vpninfo->localname);
                if (vpninfo->ip_info.addr)
```

**Comment by baergj** [comment]
Also: Let me know if I should be filing this against upstream openconnect as well; it's not clear where GP issues should go at the moment.

**Comment by dlenski** [comment]
> 5da09b1 breaks authentication against my company's VPN when running from linux-64. I receive the following:

Quick follow-up questions:

* What OS _are_ you actually using? Linux?
* Which request specifically is triggering the erroneous "Incorrect username or password"? `/global-protect/getconfig.esp` or `/ssl-vpn/login.esp`?

This report is useful… and crazy-making:

* Per the commit message of 7f7d739fe6ae059f31dfd768d7469a8fcca390f9, I have at least two reports of servers where `clientos=Windows` is _required_ for the VPN to work.
* Per _your_ report, there is at least one case where **not** setting `clientos=Windows` is _required_ for the VPN to work.
* The maddening part is not only the pointless and inconsistent behavior of the servers, but also the fact that the servers give such misleading and irrelevant error messages ("Incorrect username or password" or "Unable to assign private IP address", etc.) rather than something that makes sense like "Unknown clientos value."

> Also: Let me know if I should be filing this against upstream openconnect as well; it's not clear where GP issues should go at the moment.

Yeah, I'm not sure which one gets more eyeballs. There are starting to be GP issues reported upstream too.

**Comment by dlenski** [comment]
Also, I'm quite confused about how the official Windows client can work with your VPN (it uses `clientos=Windows`).

1. Is it possible for you to use mitmproxy to capture a log of the official client's [HTTPS authentication requests](https://github.com/dlenski/openconnect/blob/globalprotect/PAN_GlobalProtect_protocol_doc.md#login-request), to understand exactly which parameters are different/missing?

2. Could you try this alternate patch, which leaves the `clientos=Windows` alone, but throws the kitchen sink at the server in terms of including a bunch of seemingly-unnecessary parameters (parameters which have never actually appeared to make a difference in my previous testing)? If _this_ version works, then I won't need to break the automatic `clientos=Windows` spoofing…

```diff
diff --git a/auth-globalprotect.c b/auth-globalprotect.c
index 5b2d3ec1..f1d364b5 100644
--- a/auth-globalprotect.c
+++ b/auth-globalprotect.c
@@ -362,8 +362,8 @@ static int gpst_login(struct openconnect_info *vpninfo, int portal, char *pw_or_
 
                /* submit gateway login (ssl-vpn/login.esp) or portal config (global-protect/getconfig.esp) request */
                buf_truncate(request_body);
-               buf_append(request_body, "jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:&clientos=Windows");
-               append_opt(request_body, "os-version", vpninfo->platname);
+               buf_append(request_body, "jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100"
+               "&prot=https:&clientos=Windows"
+               "&os-version=Microsoft+Windows+Server+2012%2C+64-bit&clientgpversion=3.0.1-10"
+               "&portal-userauthcookie=empty&portal-prelogonuserauthcookie=empty"
+               "&host-id=deadbeef-dead-beef-dead-beefdeadbeef");
                append_opt(request_body, "server", vpninfo->hostname);
                append_opt(request_body, "computer", vpninfo->localname);
			append_opt(request_body, "preferred-ip", vpninfo->ip_info.addr);
		if (ctx->form->auth_id && ctx->form->auth_id[0]!='_')
			append_opt(request_body, "inputStr", ctx->form->auth_id);
+		else
+			append_opt(request_body, "inputStr", "");
		append_form_opts(vpninfo, ctx->form, request_body);
		if ((result = buf_error(request_body)))
			goto out;
```

**Comment by baergj** [comment]
Hey Dan, sorry, didn't see this until now. Answers/responses:

> What OS are you actually using? Linux?

Sorry, yes - Gentoo, specifically.

> Which request specifically is triggering the erroneous "Incorrect username or password"? /global-protect/getconfig.esp or /ssl-vpn/login.esp?

Doh - I see I didn't include the full sequence. I'm 90% certain that it's login.esp, but I can double-check during the work day tomorrow. I'll look into the other options then, too.

**Comment by baergj** [comment]
Quick update: The provided patch doesn't result in any change (i.e. login failure still occurs in the same way). Also, I've confirmed that the failure is in response to the login.esp request.

**Comment by baergj** [comment]
Alright, I've captured the requests from my machine. Sanitized requests below. Anything I've scrubbed I've replaced with '<>', and everything is still URL-encoded. I've added some comments to getconfig regarding where some of the non-obvious values came from.
```
getconfig 

user=<>
passwd=<>
inputStr=<>
ok=Login
clientVer=4100
portal-userauthcookie=<>
portal-prelogonuserauthcookie=
clientos=Linux
clientgpversion=4.1.2-6
computer=<> (hostname)
os-version=Linux+ (Perhaps the output of 'uname' with a space after?)
host-id=<> (/sys/class/dmi/id/product_uuid)
prelogin-cookie=
ipv6-support=yes
```
```
prelogin

tmp=tmp
clientVer=4100
host-id=<>
clientos=Linux
os-version=Linux+
ipv6-support=yes
```
```
login

prot=https:
server=<>
inputStr=<>
jnlpReady=jnlpReady
user=<>
passwd=<>
computer=<>
ok=Login
direct=yes
clientVer=4100
os-version=Linux+
preferred-ip=
preferred-ipv6=
clientos=Linux
clientgpversion=4.1.2-6
portal-userauthcookie=<>
portal-prelogonuserauthcookie=
host-id=<>
prelogin-cookie=
ipv6-support=yes
client-ip=<>
client-ipv6=
internal=no
```

**Comment by dlenski** [comment]
Okay, wait a sec… you have an *official* GP client which runs on Linux?!

**Comment by baergj** [comment]
Yes. It doesn't fully work for me, though, which is why I've been working on getting openconnect working.

**Comment by dlenski** [comment]
> ...I guess that doesn't tell us why the Windows spoofing failed here. I don't have Windows, otherwise I would snoop those requests, too - perhaps there are changes to the field values.

Can't blame you on not having Windows. :-p

Yes, exactly, I'm trying to figure why the combination of values spit out by the official 3.0.10 Windows client aren't working.

**Comment by dlenski** [comment]
Please try the latest `master` branch commit, 59d3504, which includes `Linux` among the allowed OS values.

**Comment by baergj** [comment]
Works for me! Thanks!

**Comment by baergj** [comment]
Two questions:
1. At what frequency are changes in this repo merged upstream?
2. Should I close this issue, or do you use open issues for upstream merge tracking?

**Comment by dlenski** [comment]
> Two questions:
>
> 1. At what frequency are changes in this repo merged upstream?
> 2. Should I close this issue, or do you use open issues for upstream merge tracking?

Good questions, no clear answers :joy: 

Things go upstream when I have time to organize and rebase 'em and pass them along to @dwmw2, and he has time to read and approve.

At some point I hope we can stop using this repo for bug tracking of the GlobalProtect bits, in favor of the mailing list and/or [openconnect/openconnect on Gitlab](https://gitlab.com/openconnect/openconnect/).

**Comment by baergj** [comment]
OK :)

**Comment by baergj** [comment]
Hey, just wondering if this is going to make the v8 release or not.

**Comment by baergj** [comment]
k - it's not :) I don't mind creating a merge request for it there, but I didn't want to mess with any process you had for merging things across (as I'm assuming you have a backlog of things to merge).

**Comment by dlenski** [comment]
> Not if it isn't in https://gitlab.com/openconnect/openconnect/merge_requests

Thanks for the reminder, @dwmw2. Making an MR right now: https://gitlab.com/openconnect/openconnect/merge_requests/17

**Comment by baergj** [comment]
Thanks both!
