### ISSUE TITLE
sed regex failure on MacOS

### ISSUE THREAD

**Issue by kbaegis** [dlenski/openconnect#132]
Hi all. Installed with homebrew atop MacOS. I also use the 'iproute2mac' homebrew formulae, however this appears to be failing on sed. Uncommented the `set -x` in /usr/local/etc/vpnc-script, yielding:
```
+ set_vpngateway_route
++ /usr/local/bin//ip route get <omitted>
++ fix_ip_get_output
++ sed -e 's/ /\n/g'
++ sed -ne '1p;/via/{N;p};/dev/{N;p};/src/{N;p};/mtu/{N;p}'
sed: 1: "1p;/via/{N;p};/dev/{N;p ...": extra characters at the end of p command
+ /usr/local/bin//ip route add
Usage: ip route list
       ip route get ADDRESS
       ip route { add | del } ROUTE
ROUTE := PREFIX [ nexthop NH ]


....


+ do_disconnect
+ '[' -n 39 ']'
+ i=0
+ '[' 0 -lt 39 ']'
+ eval 'NETWORK=${CISCO_SPLIT_INC_0_ADDR}'
++ NETWORK=<omitted>
+ eval 'NETMASK=${CISCO_SPLIT_INC_0_MASK}'
++ NETMASK=<omitted>
+ eval 'NETMASKLEN=${CISCO_SPLIT_INC_0_MASKLEN}'
++ NETMASKLEN=<omitted>
+ '[' <omitted> '!=' 0.0.0.0 ']'
+ del_network_route <omitted> <omitted> <omitted>
+ NETWORK=<omitted>
+ NETMASK=<omitted>
+ NETMASKLEN=<omitted>
+ /usr/local/bin//ip route del <omitted>/<omitted> dev utun1
Executing: /usr/bin/sudo /sbin/route delete <omitted>/<omitted>
route: writing to routing socket: not in table
delete net <omitted>: not in table
+ /usr/local/bin//ip route flush cache
Usage: ip route list
       ip route get ADDRESS
       ip route { add | del } ROUTE
ROUTE := PREFIX [ nexthop NH ]
```

Thanks in advance!

**Comment by dlenski** [comment]
Verrrry interesting. This appears to be related to the long-outstanding, never-resolved #93. This seems to a corner case in the way that `vpnc-script` works (or doesn't work) on macOS.

Insert standard disclaimer about how I personally don't use or understand Mac OS or its routing configuration utilities.

**Comment by XL64** [comment]
Uninstalling iproute2mac solved the same issue for me.

**Comment by luikore** [comment]
This line in vpnc-script causes the problem (it thinks the system is SunOS if there is `ip` command, but in fact it is installed by iproute2mac):

```
# stupid SunOS: no blubber in /usr/local/bin ... (on stdout)
IPROUTE="`which ip 2> /dev/null | grep '^/'`"
```

Another way to fix it is edit /usr/local/etc/vpnc-script and change the above lines to

```
# stupid SunOS: no blubber in /usr/local/bin ... (on stdout)
IPROUTE="`which ip 2> /dev/null | grep '^/'`"
if [ "$OS" = "Darwin" ]; then
  IPROUTE=
fi
```

**Comment by dlenski** [comment]
> Another way to fix is edit /usr/local/etc/vpnc-script and change the above line to…

@luikore, great sleuthing. This clears up a longstanding mystery for many macOS users, I think.

Could you post your patch and explanation on the [openconnect mailing list](http://www.infradead.org/openconnect/mail.html)?

**Comment by Ezequieltbh** [comment]
I was facing the same issue with the "ip" command.
Applied the patch of @luikore and it's working now.
Do you need help for post/test the patch? Glad to help.

**Comment by dlenski** [comment]
@ezequieltbh Yes, thanks for confirming. Can you submit a merge-request against it on gitlab? (That's where all the openconnect/vpnc-script development is happening these days.)
 
https://gitlab.com/openconnect/vpnc-scripts/merge_requests

**Comment by Ezequieltbh** [comment]
@dlenski Sure, give me a few days.
I am looking in another issue, related to DNS server configuration, I will let you know if it's related to this project.

**Comment by dlenski** [comment]
All, I submitted a merge request on Gitlab.

This should fix the problem for any and all users of non-Linux OS with `ip` in their path: https://gitlab.com/openconnect/vpnc-scripts/merge_requests/2

**Comment by napalmz** [comment]
Openconnect v.810
MacOS v.10.15.7
This is what happend:
```
Connected to KK.KK.KK.KK:443
SSL negotiation with connect.company.net
Connected to HTTPS on connect.company.net with ciphersuite (TLS1.2)-(RSA)-(AES-128-CBC)-(SHA256)
Got HTTP response: HTTP/1.1 101 Switching Protocols
Enter user credentials:
Set up UDP failed; using SSL instead
Connected as XX.XX.XX.XX, using SSL, with ESP disabled
add host KK.KK.KK.KK: gateway LOCAL.GATEWAY.IP
route: writing to routing socket: Can't assign requested address
add net XX.XX.XX.XX: gateway XX.XX.XX.XX: Can't assign requested address
add net YY.YY.YY.YY: gateway XX.XX.XX.XX
add net YY.YY.YY.YY: gateway XX.XX.XX.XX
etc
```

I've checked my vpnc-script and has all previous mentioned modifications.

**Comment by dlenski** [comment]
> Openconnect v.810
> MacOS v.10.15.7
> This is what happend:
> 
> ```
> Connected to KK.KK.KK.KK:443
> SSL negotiation with connect.company.net
> Connected to HTTPS on connect.company.net with ciphersuite (TLS1.2)-(RSA)-(AES-128-CBC)-(SHA256)
> Got HTTP response: HTTP/1.1 101 Switching Protocols
> Enter user credentials:
> Set up UDP failed; using SSL instead
> Connected as XX.XX.XX.XX, using SSL, with ESP disabled
> add host KK.KK.KK.KK: gateway LOCAL.GATEWAY.IP
> route: writing to routing socket: Can't assign requested address
> add net XX.XX.XX.XX: gateway XX.XX.XX.XX: Can't assign requested address
> add net YY.YY.YY.YY: gateway XX.XX.XX.XX
> add net YY.YY.YY.YY: gateway XX.XX.XX.XX
> etc
> ```

This tells me absolutely nothing. It doesn't even appear to be related to the issue that drove this thread.

Please create a new issue at https://gitlab.com/openconnect/vpnc-scripts/-/issues/, and be sure that you include additional debugging information about the vpnc-script as described [here](https://gitlab.com/openconnect/vpnc-scripts/-/issues/10#note_424084380).
