### ISSUE TITLE
Conflict with PAC file proxy

### ISSUE THREAD

**Issue by huangbiubiu** [dlenski/openconnect#133]
I'm using [a socks5 proxy](https://github.com/shadowsocks/shadowsocks-qt5) via Linux Network Settings with a PAC file. I found that Ubuntu Desktop network settings have higher priority than openconnect: I can't connect my school network after use PAC proxy. Are there any solutions to use them at the same time?

**Comment by dlenski** [comment]
> I found that Ubuntu Desktop network settings have higher priority than openconnect: I can't connect my school network after use PAC proxy.
> Are there any solutions to use them at the same time?

Sure… but what is it that you want to actually happen here?

Do you want traffic to go through the VPN ("school network") or through the shadowsocks proxy?

Do you want _some_ traffic to go through the VPN and _other_ traffic to go through the shadowsocks proxy? Presumably you should modify the PAC file to not send traffic to the VPN gateway or VPN-internal hosts through the proxy… right? ¯\\\_\(ツ)\_/¯
