### ISSUE TITLE
Set up tun device failed

### ISSUE THREAD

**Issue by ancoleman** [dlenski/openconnect#134]
I get this when running in the docker container:

HIP report submitted successfully.
Parameters for incoming ESP: SPI 0x19b64663
ESP encryption type AES-128-CBC (RFC3602) key 0x8e874c6e803276551d0b850b2e92a290
ESP authentication type HMAC-SHA-1-96 (RFC2404) key 0x848fd59fa81714772a7929fedcc62cae86a83ed2
Parameters for outgoing ESP: SPI 0x3bf84cf3
ESP encryption type AES-128-CBC (RFC3602) key 0xe5d54afa702be891b0bfcbfb12ec36e3
ESP authentication type HMAC-SHA-1-96 (RFC2404) key 0x959a806927c6f0bd22243bd8fab92a279fce3d96
Send ESP probes
Connected as 192.168.38.7, using SSL, with ESP in progress
Failed to bind local tun device (TUNSETIFF): Operation not permitted
To configure local networking, openconnect must be running as root
See http://www.infradead.org/openconnect/nonroot.html for more information
Set up tun device failed
Unknown error; exiting.

But I'm running as root in the container

**Comment by dlenski** [comment]
Your post doesn't contain enough information to make progress. Please read the [issue template](https://github.com/dlenski/openconnect/blob/HEAD/.github/issue_template.md) and provide more detailed logs.

Also, I don't know a lot about Docker, but you need to specifically allow a container to access network interfaces: https://docs.docker.com/v17.09/engine/userguide/networking/

Being root _inside_ the container isn't enough.

**Comment by jansenicus** [comment]
the solution for this docker privileged problem is to add the `--privileged` option:
```
docker run -it --privileged mydockerimage
```
