### ISSUE TITLE
MacOS system proxy settings ignored

### ISSUE THREAD

**Issue by Igogrek** [dlenski/openconnect#138]
I'm using openconnect on MacOS (Mojave 10.14.1) to connect to remote network. Remote network is protected by proxy for internet access (local network machines are reachable directly). 
After I connect to the VPN - I'm able to connect to remote network machines no problem, but internet is not accessible - system-wide proxy settings are ignored for some reason (Network Preferences -> Advanced -> Proxies -> Web Proxy).
As far I understand - after connection to VPN is established all of the traffic is routed to the remote network which blocks direct internet access.

I've tried playing around with proxy settings in both UI and from terminal, tried setting env variables like HTTP_PROXY - no luck. 
For browser it's possible to fix with some proxy switcher plugin (switch to proxy after connecting to VPN manually, disable after VPN disconnect), but other applications, like Slack are not able to connect anymore at all.

Retested on multiple other machines - same behaviour.
I understand that I could use https://github.com/dlenski/vpn-slice to specifically route only specific traffic to "parent" network, but I think proxy should also work somehow.

Any idea how to make proxy work after connecting to VPN in this case?

**Comment by dlenski** [comment]
(This might be related to #133, hard for me to tell.)

> As far I understand - after connection to VPN is established all of the traffic is routed to the remote network which blocks direct internet access.

Correct.

> I understand that I could use https://github.com/dlenski/vpn-slice to specifically route only specific traffic to "parent" network, but I think proxy should also work somehow.

Yes, it's entirely possible to send all your traffic through the VPN, but _also_ use the (VPN-internal) proxy for internet-bound traffic. However, this is OS-dependent and entirely outside the scope of what openconnect itself does.

Insert standard disclaimer about how I don't personally use macOS or know much of anything about its routing and networking configuration tools.
