### ISSUE TITLE
Minor issue: get-globalprotect-config.py is not working for me

### ISSUE THREAD

**Issue by samm-git** [dlenski/openconnect#14]
Hi, 

1. Huge thanks for making this app. I am osx user and i hate official client with all issues it involves. Your app works for me! And of course i can edit vpn script to add only routes i wont/need, dont touch default, etc.
2. /get-globalprotect-config.py for me returns no config, not sure if its something you can fix 
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<policy>
<has-config>no</has-config>
<user-group-loaded>yes</user-group-loaded>
<portal-userauthcookie>empty</portal-userauthcookie>
<portal-prelogonuserauthcookie>empty</portal-prelogonuserauthcookie>
</policy>
```
3. In my configuration there is a country list with vpn in every country. Its shown in the menu. I think its requested from the portal at some point. Is it possible to show them in the script?

P.S. are you planning to merge your changes back to the openconnect? would be great to have support in the mainline

**Comment by dlenski** [comment]
I'm glad it's working well for you! Yes, I expect this will be merged into the official mainline at some point. You can find discussions of it on the OpenConnect-devel mailing list.

I'm a bug confused by your question. In #2, you say that the script returns no config. This is something I haven't seen before. But in #3, you mention that the config contains gateways for many different countries. Where does that config come from, then? How do you access it?

**Comment by dlenski** [comment]
Also, see the [gp-portal branch](https://github.com/dlenski/openconnect/tree/gp-portal) which tries to get a list of the available gateways from the portal, and gives the user the option to choose among them.

**Comment by dlenski** [comment]
@samm-git, please fill in more details of the problem.
