### ISSUE TITLE
how can we compile it for windows

### ISSUE THREAD

**Issue by ilovefood2** [dlenski/openconnect#152]
I'm looking for a windows commandline version of openconnect, but i can't seem to find any. 
so I'm thinking there should be a way to compile it from source for windows version. Could anyone please help with how to achieve it ? 

thanks

**Comment by dlenski** [comment]
https://github.com/openconnect/openconnect-gui includes a CLI build for Windows.

**Comment by ilovefood2** [comment]
yes, but that's v7 though, i'm thinking about a v8 though

**Comment by ilovefood2** [comment]
i tried with https://github.com/openconnect/openconnect-gui and compiled from script, somehow still not able to connect to globalprotect

**Comment by ilovefood2** [comment]
i figured out, based on https://github.com/openconnect/openconnect-gui/tree/develop/contrib
the compiled windows works fine with other ssl vpn, but globalprotect does not work, it turned out the vpnc-script-win.js has errors with adding gateway and dns server address. 
thank you
case closed.
