### ISSUE TITLE
override X-CSTP-Tunnel-All-DNS

### ISSUE THREAD

**Issue by FernandoMiguel** [dlenski/openconnect#155]
# Problem description

1. sudo openconnect -v --timestamp --user=fernando vpn.xxxx.com
2. `[2019-10-06 13:46:42] X-CSTP-Tunnel-All-DNS: true`

# Operating system and openconnect-gp version

openconnect-gp version:

```
openconnect --version
OpenConnect version v8.05
Using GnuTLS. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp, pulse
```

operating system

```
Darwin fmMac6.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 21:13:50 PDT 2019; root:xnu-6153.11.26~4/RELEASE_X86_64 x86_64
```

I run dnscrypt-proxy on my laptop. it already has forwarding rules for the company domains.

but since the VPN forces `X-CSTP-Tunnel-All-DNS: true` , my entire OS doesnt follow my DNS server , but the one provided by the VPN.

Is there a way i can locally override that?

**Comment by dlenski** [comment]
(By the way, this isn't related to GP support, and this repository mostly only still exists for historical reasons… I should maybe disable new issues here.)

To your question, though…

> since the VPN forces `X-CSTP-Tunnel-All-DNS: true`, my entire OS doesnt follow my DNS server , but the one provided by the VPN.

This is incorrect. The official Cisco clients slavishly follow what the VPN server tells them to do (Cisco cares a lot more about IT departments than about end users :sweat_smile:), but OpenConnect actually _does not pay attention to this flag at all_.

All of OpenConnect's routing setup is done by [a script called `vpnc-script`](https://gitlab.com/openconnect/vpnc-scripts). The _default_ `vpnc-script` follows the routing instructions sent by the VPN server, which normally means replacing the default DNS server and setting the default route to go through the VPN…

… but you can easily use the `-s`/`--script` option to invoke an alternate `vpnc-script`, such as [vpn-slice](https://github.com/dlenski/vpn-slice/), which I wrote for the exact purpose of not wanting to route _anything_ through the VPN _by default_, while making it easy to route _explicitly specified_ hosts and subnets through the VPN.

**Comment by FernandoMiguel** [comment]
Traffic wise, it is only sending the ones it has routes for.
It's the DNS that is being all sent to the vpn endpoint instead of my DoH local stub.
I had previously taken a look at vpn slice and it doesn't seem to add anything that the client and server push rules already do.

When you say the flag is ignored, my experience shows it otherwise, as a dig clearly shows that DNS being used.

**Comment by dlenski** [comment]
> Traffic wise, it is only sending the ones it has routes for.

I don't know what this means.

> It's the DNS that is being all sent to the vpn endpoint instead of my DoH local stub.

What is a DoH local hub?

Again, the DNS is going through the VPN because…

1. The VPN sends some `CONNECT` headers like this…
```
X-CSTP-Version: 1
X-CSTP-Protocol: Copyright (c) 2004 Cisco Systems, Inc.
X-CSTP-Address: 10.10.10.123
X-CSTP-Netmask: 255.255.248.0
X-CSTP-DNS: 10.10.10.1
X-CSTP-DNS: 10.10.10.2
X-CSTP-Tunnel-All-DNS: true
```
2. OpenConnect captures the `X-CSTP-DNS` headers and passes them along the `vpnc-script`.
3. The `vpnc-script` sets up the routing as provided by the VPN *and* it sets the default DNS servers to the ones provided by the VPN _without regard to `X-CSTP-Tunnel-All-DNS`.


> I had previously taken a look at vpn slice and it doesn't seem to add anything that the client and server push rules already do.

Did you actually _try_ it? I wrote `vpn-slice`, and use it every day, for the specific purpose of not following the routes and DNS servers sent by the VPN.

> When you say the flag is ignored, my experience shows it otherwise, as a dig clearly shows that DNS being used.

Again, this is not correct. Look at the source code (specifically the section of `cstp.c` that parses the `X-CSTP` headers) and you will see that OpenConnect does not use this flag at all.

**Comment by FernandoMiguel** [comment]
thanks for the clarification.
i'll give slice a try.

> What is a DoH local hub?
stub, not hub. it's just a dns server redirecting requests to another server, via DoH

**Comment by FernandoMiguel** [comment]
@dlenski working flawlessly 
thanks for the great tools and support
