### ISSUE TITLE
Unable to build for Android

### ISSUE THREAD

**Issue by AkshatAgrawal05** [dlenski/openconnect#158]
Hi, 

I want to create binaries for android but in doing so getting error

``  CCLD     libgnu_gpl.la
make[5]: Leaving directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls/src/gl'
make[4]: Leaving directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls/src/gl'
make[3]: Leaving directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls/src/gl'
Making all in src
make[3]: Entering directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls/src'
make  all-recursive
make[4]: Entering directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls/src'
make[5]: Entering directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls/src'
  CC       psktool-args.lo
clang50: error: no such file or directory: 'psktool-args.c'
clang50: error: no input files
make[5]: *** [psktool-args.lo] Error 1
make[5]: Leaving directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls/src'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls/src'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/mnt/d/Apk_source/vpn/openconnect/android/arm-linux-androideabi/gnutls'
Makefile:242: recipe for target 'arm-linux-androideabi/gnutls/lib/libgnutls.la' failed
make: *** [arm-linux-androideabi/gnutls/lib/libgnutls.la] Error 2
make: Leaving directory '/mnt/d/Apk_source/vpn/openconnect/android'

I installed all the dev tools, build essentials. 

Please help.

**Comment by dlenski** [comment]
This is a repo that still exists only for historical reasons around GP development. Issues with OpenConnect in general should use
https://lists.infradead.org/mailman/listinfo/openconnect-devel.
