### ISSUE TITLE
connect to server without ID pass

### ISSUE THREAD

**Issue by naziur604** [dlenski/openconnect#161]
i have installed ocserv on my debian server
i want to connect openconnect app to server without id pass
every time enter id pass its a pain so if you have any idea how to do that
please let me know

**Comment by dlenski** [comment]
This is a repo that still exists only for historical reasons around GP development. Issues with OpenConnect in general should use
https://lists.infradead.org/mailman/listinfo/openconnect-devel, and also provide a much more coherent and complete problem description than what you've posted here.
