### ISSUE TITLE
Unknown VPN protocol 'gp'

### ISSUE THREAD

**Issue by edgarcaldeira** [dlenski/openconnect#166]
Hi Guys, i'm trying to use openconnect and when i ran the code i get the message below:

# openconnect --protocol=gp 125.212.xxx.x --dump -vvv
RESULT:
Unknown VPN protocol 'gp'

My openconnect version:
OpenConnect version v7.08-3ubuntu0.18.04.1
Using GnuTLS. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS

OS:

uname -a
Linux edgar-linux 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Anyone could give me a light here?

Thanks !

**Comment by dlenski** [comment]
Did you read the README? :roll_eyes: 

![screenshot](https://snipboard.io/YJmBou.jpg)
