### ISSUE TITLE
How to configure the virtual network adapter MTU size

### ISSUE THREAD

**Issue by 512676155** [dlenski/openconnect#169]
Created a virtual network adapter MTU size above target network MTU, led to the packet loss when using SSH connection network server, Although MTU size can be manually modify after connected VPN , but I wonder if there is a kind of way can change the default MTU size in configuration, which can make the default MTU  of a smaller value

**Comment by dlenski** [comment]
I don't really understand what you're trying to do (in particular why you're creating a VPN adapter "by hand").
