### ISSUE TITLE
2FA error

### ISSUE THREAD

**Issue by 0atman** [dlenski/openconnect#17]
# Problem description

`Failed to obtain WebVPN cookie`

```shell
$ openconnect --protocol=gp [gateway ip] --dump -vvv             
Please enter your username and password.
Username: 0atman
Password: 
POST https://[gateway ip]/ssl-vpn/login.esp
Attempting to connect to server [gateway ip]:443
Connected to [gateway ip]:443
SSL negotiation with [gateway ip]
Server certificate verify failed: signer not found

Certificate from VPN server "[gateway ip]" failed verification.
Reason: signer not found
To trust this server in future, perhaps add this to your command line:
    --servercert sha256:12345[...]
Enter 'yes' to accept, 'no' to abort; anything else to view: yes

Connected to HTTPS on [gateway ip]
> POST /ssl-vpn/login.esp HTTP/1.1
> Host: [gateway ip]
> User-Agent: PAN GlobalProtect
> X-Pad: 000000000000000000000000000000000000000000000
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 147
> 
> jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:&server=[gateway ip]&computer=[hostname]&user=0atman&passwd=[password]
Got HTTP response: HTTP/1.1 200 OK
Server: 
Date: Thu, 06 Apr 2017 14:37:45 GMT
Content-Type: text/html
Content-Length: 181
Connection: keep-alive
ETag: "6bde3-1e54-57ae21b7"
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-FRAME-OPTIONS: DENY
Set-Cookie: PHPSESSID=[php session id]; secure; HttpOnly
Set-Cookie: PHPSESSID=[php session id]; secure; HttpOnly
Set-Cookie: PHPSESSID=[php session id]; secure; HttpOnly
HTTP body length:  (181)
< 
< var respStatus = "Challenge";
< var respMsg = "Enter PIN and One Time Password e.g. if your PIN is 1234 and OTP is 111111 then type 1234111111  ";
< thisForm.inputStr.value = "1169";
< 
Enter PIN and One Time Password e.g. if your PIN is 1234 and OTP is 111111 then type 1234111111  
Failed to obtain WebVPN cookie
```
# Operating system and openconnect-gp version

## openconnect-gp version
`OpenConnect version v7.08-1ubuntu5
Using GnuTLS. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS`

## operating system
`Linux oatman-MacBookPro 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

# GlobalProtect VPN information

No connection made

**Comment by dlenski** [comment]
Please build the latest version from source. The changes to support 2FA challenge authentication were merged in #12, and they are not yet in the Ubuntu/deb package.

**Comment by dlenski** [comment]
You can also use the [globalprotect-challenge-login.py](https://github.com/dlenski/openconnect/blob/globalprotect/globalprotect-challenge-login.py) Python script to quickly whether challenge login works.

**Comment by 0atman** [comment]
Thank you! I had not noticed that discrepancy. I will try it first thing MONDAY. 
EXCITEMENT BUILDING!

**Comment by dlenski** [comment]
Let me know how it works. I don't have access to any GP VPN with challenge auth, so I wrote the code entirely based on another user's description. (And it does work for that user.)

**Comment by 0atman** [comment]
As mentioned in other threads, this totally worked :-)
