### ISSUE TITLE
OpenConnect-gp fails to rekey at the specified interval

### ISSUE THREAD

**Issue by suedeworthey** [dlenski/openconnect#173]
# Problem description

1. I ran openconnect-gp as follows: `openconnect --protocol=gp -v --timestamp --os=win --cafile <ca_file_path> --csd-wrapper=/usr/libexec/openconnect/hipreport.sh --servercert pin-sha256:<server_cert_pin> --user=<user_name> <VPN_GATEWAY_IP>`
2. Once the rekey interval expired (15 minutes in this case), openconnect does not attempt to rekey. Instead, it closes the session and tries to reconnect.
Broken code: (ssl.c:1048-1054)
`	case DTLS_ESTABLISHED:
		/* Rekey or check-and-resubmit HIP if needed */
		if (keepalive_action(&vpninfo->ssl_times, timeout) == KA_REKEY)
			goto do_rekey;
		else if (trojan_check_deadline(vpninfo, timeout))
			goto do_recheck_hip;
		return 0;
`
4. VPN Fails, disconnects, and I have to reconnect. The rekey interval cannot be changed, so I get 15 minutes at a time. This is effectively useless.

# Operating system and openconnect-gp version

openconnect-gp version:

```
openconnect --version
OpenConnect version v9.01
Using GnuTLS 3.7.7. Features present: TPM, TPMv2, PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp, pulse, f5, fortinet, array
Default vpnc-script (override with --script): /etc/vpnc/vpnc-script
```

operating system

```
Linux mpls-ws-4c82 5.18.17-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 11 14:36:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

# GlobalProtect VPN information

```
<!--
This information isn't necessary for this bug's resolution.
-->
```

**Comment by dlenski** [comment]
Did you read the README? 

>You don't want this repository. **It is retained only for historical purposes.**
>
> [OpenConnect v8.00](http://lists.infradead.org/pipermail/openconnect-devel/2019-January/005178.html) has now been released. (Actually, we're several versions past that at this point.)
>
> OpenConnect v8.x includes GlobalProtect support, as developed in this repository, out-of-the-box.

Please file this at https://gitlab.com/openconnect/openconnect/-/issues so we can discuss with other developers.

**Comment by suedeworthey** [comment]
Will do. Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
