### ISSUE TITLE
using network-manager

### ISSUE THREAD

**Issue by paraglade** [dlenski/openconnect#20]
I would like to be able to use network-manager to manage my openconnect vpn connections with the GP protocol however there is not an option in the VPN setup dialog to set the protocol. Can this be done by some other means?

**Comment by dlenski** [comment]
Oops, sorry, didn't mean to close this. Good timing!

I have been working on adding support for switching protocols to the Network Manager plugin and it is working perfectly for me now. I posted a screenshot on the openconnect mailing list recently.

I need to clean up the code for the NM plugin a bit and will upload it in a day or two.

**Comment by dlenski** [comment]
See here: https://github.com/dlenski/network-manager-openconnect

You'll need to build openconnect from the `globalprotect` branch and network-manager-openconnect from the `multiprotocol` branch and the two should work together then :+1:

![screenshot from 2017-04-09 01-53-48](https://cloud.githubusercontent.com/assets/128716/25066154/44629fae-21d3-11e7-830a-d0821435b75d.png)

**Comment by inetman** [comment]
@dlenski 
Could you please detailt information about how install it for dummes? ;)

**Comment by inetman** [comment]
ping )

**Comment by dlenski** [comment]
@inetman, there is no "for dummies" installation method right now.

Either figure out how to build it from source (not too hard) or wait for me to build Ubuntu/.deb packages (I'll get around to it eventually).

**Comment by sandeep-khanna** [comment]
Was the Gnome/Ubuntu network manager and/or editor package built/updated to include the GlobalProtect option in the VPN Protocol dropdown?

I am using Ubuntu MATE 19.04 with OpenConnect version v8.02-1 and able to use GlobalProtect on the command-line as:
user@linux:~$ sudo openconnect --protocol=gp remote.vpnserver.com

Hoping to not have to use 'sudo' and preferably using the Ubuntu MATE Network Manager applet for just connecting to the GlobalProtect VPN.

**Comment by patchon** [comment]
Hi, 

Just wanted to let you know that I filed an enhancement request for this to be packaged and used upstream for Fedora. I've been using this for quite a while and it works as expected. I'm talking about the dynamic-list-generation for supported "protocols" in the VPN Protocol dropdown menu in the NetworkManager VPN Connection editor.

https://bugzilla.redhat.com/show_bug.cgi?id=1720580

**Comment by ericsysmin** [comment]
@sandeep-khanna  I think it's being worked on here https://gitlab.gnome.org/GNOME/NetworkManager-openconnect/merge_requests/6

**Comment by caujka** [comment]
Here is my workaround:
```
$ nmcli connection
   # it prints connections available. Pick the one that has the wrong protocol.
$ nmcli connection edit "vpn 1"
   # it enters interactive edit mode.
> print vpn.data
    # it prints the connection parameters. Edit them in some text editor,
    # so that   protocol = gp.
> set vpn.data <your_changed_parameters_line>
> save
```
voilla, the connection has the right protocol.

**Comment by antselK** [comment]
> Here is my workaround:
> 
> ```
> $ nmcli connection
>    # it prints connections available. Pick the one that has the wrong protocol.
> $ nmcli connection edit "vpn 1"
>    # it enters interactive edit mode.
> > print vpn.data
>     # it prints the connection parameters. Edit them in some text editor,
>     # so that   protocol = gp.
> > set vpn.data <your_changed_parameters_line>
> > save
> ```
> 
> voilla, the connection has the right protocol.

After protocol change VPN connection is successful, but it does not work for me. No packets are moving.
