### ISSUE TITLE
Autoheader Error

### ISSUE THREAD

**Issue by iwanttobefreak** [dlenski/openconnect#3]
Hello. I'm trying to build from git and I have this error:

```
# ./autogen.sh 
autoheader: warning: missing template: LIBPROXY_HDR
autoheader: Use AC_DEFINE([LIBPROXY_HDR], [], [Description])
```

SO: ubuntu 15.04

Thanks

**Comment by dlenski** [comment]
I haven't run into this. Is the `libproxy-dev` package installed?

**Comment by iwanttobefreak** [comment]
Yes, I have installed libproxy-dev.
With debian same problem.
With centos works

**Comment by dlenski** [comment]
I haven't changed anything about the proxy handling in this fork/branch. I'm not able to reproduce this on Ubuntu **16.04** or **14.04**; `./autogen.sh` does not seem to require `libproxy-dev`.

It looks like what you're getting is only a warning message. Has `configure` been created afterward running `autogen.sh`?

**Comment by bc-hill** [comment]
I am encountering an identical error.  New Debian Stable install.

configure is not created.

> $ ./autogen.sh 
> autoheader: warning: missing template: LIBPROXY_HDR
> autoheader: Use AC_DEFINE([LIBPROXY_HDR], [], [Description])
> $ uname -a
> Linux B-PC 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by dlenski** [comment]
@bc-hill, how about `config.h.in` … is that created? That's _all_ that `autoheader` is supposed to do.

Here are the contents of `autogen.sh`:

```sh
#!/bin/sh

aclocal -I m4 && \
${LIBTOOLIZE:-libtoolize} --automake --force && \
autoheader --force &&
automake --foreign --add-missing --force && \
autoconf --force
```

What happens if you run the last three commands, starting with `autoheader --force`, one by one and manually?

Does `configure` get created then?

**Comment by dlenski** [comment]
And are you able to build the official `openconnect` v7.06 package from the [Debian source package](https://packages.debian.org/source/sid/openconnect)?

This version does not differ from it in any meaningful way; it has no new dependencies and no new build scripts.

**Comment by bc-hill** [comment]
Well, apparently it was a dependency issue for me.  After building the regular openconnect package, I am able to build your fork.

Thank you.  Now just need to get it working fully.

**Comment by dlenski** [comment]
@bc-hill, which was the missing dependency? Maybe I should add it to the instructions!

Using `openconnect --dump -vv --protocol=gp` may help debug the authentication process!

**Comment by bc-hill** [comment]
@dlenski I was missing a ton of libraries.  Maybe you can just reference the openconnect build requirements for those of us who are unfamiliar with the project.

**Comment by dlenski** [comment]
> Maybe you can just reference the openconnect build requirements …

Good suggestion, done!

**Comment by ljani** [comment]
> which was the missing dependency?

For me it was `pkg-config`, which caused the error.

**Comment by robertwessen** [comment]
@dlenski This issue was not resolved for me until  installing `pkg-config` as mentioned by @ljani above. I believe this should be added to the dependencies in the current build instructions.

**Comment by drcharlieroot** [comment]
i have the same issue on freebsd (12-current, with dependencies installed),
has anyone successfully built on BSD?

**Comment by jusondac** [comment]
i'am on ubuntu 18.04,, and i got this problem
