### ISSUE TITLE
build with cygwin on Windows

### ISSUE THREAD

**Issue by dcarolino** [dlenski/openconnect#30]
Hi.

First of all, thank you @dlenski for the time dedicated to make this.

We're already using this at Linux, but since GlobalProtect client is a pain in the ass in Windows, I wonder if I can use openconnect-gp in Windows too.

I've tried to build it using cygwin without success. I apparently have all the dependencies, but still got the error below:

```
$ ./autogen.sh
' is already registered with AC_CONFIG_FILES.
/usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from...
configure.ac:1023: the top level
autom4te-2.69: /usr/bin/m4 failed with exit status: 1
aclocal-1.14: error: echo failed with exit status: 1
```

Any idea about what can be wrong? Is there another way to build this in Windows?

**Comment by dlenski** [comment]
> … since GlobalProtect client is a pain in the ass in Windows.

You're welcome. I started writing this out of sheer desperate/angry necessity :stuck_out_tongue_closed_eyes:

> Any idea about what can be wrong? Is there another way to build this in Windows?

I have never tried to build openconnect on Windows and I don't have a system with Cygwin to test it. The good news, as explained on the README, is that the **build requirements for this version are no different from recent official releases**, so I think that in this case it would be reasonable to ask for Windows build help on the [official mailing list](http://www.infradead.org/openconnect/mail.html).

**Comment by dlenski** [comment]
Any updates? I'm going to close this otherwise, since it doesn't appear to be specific to this fork, but a general issue with building OC on Windows…
