### ISSUE TITLE
Error building on MacOS: "Build with OpenSSL or GnuTLS instead."

### ISSUE THREAD

**Issue by qballer** [dlenski/openconnect#31]
# Problem description

When trying to compile from source i get the following error message 
Build with OpenSSL or GnuTLS instead. 

# Operating system :

    System Software Overview:

      System Version: macOS 10.12.1 (16B2555)
      Kernel Version: Darwin 16.1.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: wix’s MacBook Pro (2)
      User Name: Doron Tsur (doront)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 23:22

`openconnect-gp version:`

latest from source

**Comment by dlenski** [comment]
1. Your "problem description" doesn't give any context for *where* you get the error message. Please add the context from `./configure` or whatever tool is failing.
2. Did you [read the MacOS instructions](https://github.com/dlenski/openconnect/blob/globalprotect/README.md#building-on-the-mac), helpfully added to the README by another MacOS user in #10?
3. The build requirements for this version are **[the same as the official version of OpenConnect](https://github.com/dlenski/openconnect#building-from-source-on-linux)**. If you can build the official openconnect successfully, you should be able to build this version too (again, thanks to patches by same MacOS user in #9).

**Comment by dlenski** [comment]
Any updates? I'll close this if not.
