### ISSUE TITLE
Make Error On CentOS 7

### ISSUE THREAD

**Issue by jonesbf** [dlenski/openconnect#34]
Many thanks for putting this mod together, I am excited to see it working!  I run into a fatal error while trying to create the makefile. I believe the issue revolves around OpenSSL.  I'm not sure if it's due to my OS using an backported, extinct version of OpenSSL though.  Can you take a look at the error output and tell me what you think?  

On the one hand, CentOS is designed for stability so I am reluctant to "mess" with the backported OpenSSL version that is "up-to-date" for CentOS.  But, OTOH, I really need VPN access to my data via GlobalProtect so I am open to building a /usr/local, current version of OpenSSL if your mod actually needs/uses features of the most recent OpenSSL.  To put it succintly, I am not sure if the outdated, backported version of OpenSSL is instigating a red herring or something else is going on here. Thanks

```
$ uname -a
Linux localhost.localdomain 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ yum list installed | grep openssl.
openssl.x86_64                         1:1.0.1e-60.el7_3.1             @updates 
```

```
$ ./configure --prefix=/usr/local/openconnect --without-openssl-version-check
```

./configure threw a warning about using an outdated OpenSSL. I chose to silence it after confirming that RedHat backported a fix for HeartBleed, etc.

Here is the fatal error:

```
$ make check
  CC       libopenconnect_la-openssl-esp.lo
openssl-esp.c: In function 'init_esp_ciphers':
openssl-esp.c:84:58: error: 'struct esp' has no member named 'secrets'
   ret = EVP_DecryptInit_ex(esp->cipher, encalg, NULL, esp->secrets, NULL);
                                                          ^
openssl-esp.c:86:58: error: 'struct esp' has no member named 'secrets'
   ret = EVP_EncryptInit_ex(esp->cipher, encalg, NULL, esp->secrets, NULL);
                                                          ^`
openssl-esp.c: In function 'setup_esp_keys':
`openssl-esp.c:158:68: error: expected expression before '||' token
       !RAND_bytes((void *)&esp_in->enc_key, vpninfo->enc_key_len)) ||`
                                                                    ^
openssl-esp.c:159:68: error: expected statement before ')' token
       !RAND_bytes((void *)&esp_in->hmac_key, vpninfo->hmac_key_len)) ) {
                                                                    ^
openssl-esp.c:159:70: error: expected statement before ')' token
       !RAND_bytes((void *)&esp_in->hmac_key, vpninfo->hmac_key_len)) ) {
                                                                      ^
make: *** [libopenconnect_la-openssl-esp.lo] Error 1
```

**Comment by dlenski** [comment]
Hi @jonesbf… it looks like you posted this on the official mailing list as well, right?

(As I mention in the README, the build requirements for this version of openconnect are the same as the official version. It has no new dependencies. I agree that the required version of the libraries is confusing, so I [requested clarification about that as well](http://lists.infradead.org/pipermail/openconnect-devel/2017-May/004354.html).)

That said… it looks like the error you're getting is from having a partially out-of-date source tree. The `esp->secrets` was removed in e43cf0ae600e357ff4f631a063c25339808ba909. Please pull the latest version of the `globalprotect` branch and ensure that you're building from a clean source tree.

**Comment by dlenski** [comment]
> That said… it looks like the error you're getting is from having a partially out-of-date source tree. The `esp->secrets` member was replaced in e43cf0a. Please pull the latest version of the `globalprotect` branch and ensure that you're building from a clean source tree.

Nope nope nope… shame on me. I didn't actually test those changes when building with OpenSSL, only with GnuTLS. There was a mistake in my code, not in how you were building.

Please pull the latest `globalprotect` branch, where I patched the broken `openssl-esp.c`. I tested that it builds and works with a recent version of OpenSSL.

**Comment by jonesbf** [comment]
Thanks, Dan, I can confirm the patch worked with one caveat.  There are no more openssl-esp.c errors but there is 1 warning:
`esp.c: In function 'esp_catch_probe_gp':`
`esp.c:214:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    && *((in_addr_t *)(pkt->data + 12)) == vpninfo->esp_magic /* source == magic address */`

You also mentioned a similar issue reported on the mailing list.  Is it customary to use this GitHub to report issues only and use the mailing list for build help and config issues?  I'm having MTU issues and stuck at "Send ESP probes for DPD" regardless of whether I install with OpenSSL or with GnuTLS.  Which route do you suggest I file thru, GitHub or mailing list?  Thanks

**Comment by dlenski** [comment]
Great!

> _type-punning warning_

Hmm… what version of `gcc` are you building with? I thought I squashed this warning already. Doesn't show up for me with v5.4.1.

> Is it customary to use this GitHub to report issues only and use the mailing list for build help and config issues? 

For issues specific to this GlobalProtect fork, keep them on Github unless/until it is merged into the mainline, please.

> I'm having MTU issues and stuck at "Send ESP probes for DPD"…

As a temporary workaround, try running with `--no-dtls` (slower but fully-functional HTTPS tunnel, more reliable than the ESP tunnel in many cases when the GP server is misconfigured).

For getting ESP to work, you should open a new issue and post the (lightly-anonymized) log of `openconnect -vvvv --dump` and we can take a look at what's not working in the ESP setup.

**Comment by jonesbf** [comment]
On CentOS 7, my `gcc` is `gcc.x86_64` with version `4.8.5-11.el7`.  The `el7` at the tail end makes me suspect that it might not be a straightforward, outdated version of yours (v5.4.1) but one with possible backported fixes as RedHat is accustomed to do.

On a separate query: `gcc --version`
`gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)`

I reconfigured and rebuilt with GnuTLS and still show the same warning at the same point.  I think I will stay with GnuTLS instead of OpenSSL.  After searching around, it looks like to me that GnuTLS has better performance as of 2017 when given the option between the two crypto libraries.

**Comment by dlenski** [comment]
The warning is basically harmless but I should be able to fix it.

> I reconfigured and rebuilt with GnuTLS and still show the same warning at the same point. I think I will stay with GnuTLS instead of OpenSSL. After searching around, it looks like to me that GnuTLS has better performance as of 2017 when given the option between the two crypto libraries.

GnuTLS is definitely the better choice. The GnuTLS lead developer, Nikos, is also a leading OpenConnect developer and proponent (http://nmav.gnutls.org/2013/11/inside-ssl-vpn-protocol.html).

**Comment by jonesbf** [comment]
> The warning is basically harmless but I should be able to fix it.

Glad to hear that, thanks!

> As a temporary workaround, try running with `--no-dtls`

Nice, I think it arrived at a fully functional waypoint.  Is this continual response loop what's expected?

`Connected as 10.xxx.xxx.xxx, using SSL`
`Send GPST DPD/keepalive request`
`Got GPST DPD/keepalive response`
`Send GPST DPD/keepalive request`
`Got GPST DPD/keepalive response`
etc.

**Comment by dlenski** [comment]
Indeed. If you can access the internal network now, you have a functional connection.

(Also, try rebuilding with the latest commit 2d547f887c844903aeb9879a052f8d561e060ed3, mentioned above. It should fix the warning, and there's a _small_ chance that it will actually fix your ESP issue and make it work with ESP.)

**Comment by jonesbf** [comment]
Thanks again, Dan, the warning is fixed.  No dice on the ESP issue; I'll file another after I collect all of the needed info and redact it.

**Comment by dlenski** [comment]
> No dice on the ESP issue…

> I'm having MTU issues and stuck at "Send ESP probes for DPD"…

By the way, I'm not sure why you think anything at all is **wrong**. Are you actually trying to *use* this VPN, or just demonstrate that you can connect? :stuck_out_tongue:

If you run `openconnect --prot=gp`, this is the only message you'll ever see repeated, unless you enable a very high verbosity level (`-vvvv`). This is a perfectly normal log output if you connect to the ESP tunnel but then don't actually use it. You're just seeing openconnect send packets to keep the connection alive…

```
$ openconnect --protocol=gp server.company.com -u my.username -v
...
Send ESP probes
Connected as 10.19.241.137, using SSL
ESP session established with server
ESP tunnel connected; exiting HTTPS mainloop.
Send ESP probes for DPD
Send ESP probes for DPD
Send ESP probes for DPD
...
(repeated every ~10seconds)
```

So you should double-check if your VPN is not, in fact, working just fine.

**Comment by jonesbf** [comment]
> By the way, I'm not sure why you think anything at all is wrong. Are you actually trying to use this VPN, or just demonstrate that you can connect? 😛
If you run openconnect --prot=gp, this is the only message you'll ever see repeated, unless you enable a very high verbosity level (-vvvv). This is a perfectly normal log output if you connect to the ESP tunnel but then don't actually use it. You're just seeing openconnect send packets to keep the connection alive…

Hahaha, yeah I will readily admit that I do not know what the "properly functioning" response is.  I just concluded that if the ESP probes are sent out and no response is received, that something is off.  I could not find anything in the OpenConnect manual that details what the proper expected response is.

When I use the `-vvvv -dump` flags, I see the full trip of `Send ESP Probes..`, `Received ESP packet...`, and `No work to do..`. I tested out my tunneled SQL DB connection and was successful in pulling a table with rows.

Yep, I agree with you that it's functioning just fine.  All that's left, I believe, is to fix the unconfigured MTU packet size for a little, potential boost. Thanks, Ben

**Comment by dlenski** [comment]
> Yep, I agree with you that it's functioning just fine.

Good to know.

> All that's left, I believe, is to fix the unconfigured MTU packet size for a little, potential boost. Thanks, Ben

I assume you're referring to this?

```
TCP_INFO rcv mss 1300, snd mss 1300, adv mss 1460, pmtu 1500
No MTU received. Calculated 1410
```

This is something that cannot be fixed on the client side, and probably not even on the VPN admin side. 

As far as I can tell, the programmers who wrote the GP VPN server added a field to specify the MTU, but somehow left out the mechanism to fill it in :angry:. Literally every GP VPN I've seen sends `<mtu>0</mtu>` … so the client has to guess. Bad/broken design.
