### ISSUE TITLE
I'm getting "configure.ac:202: error: required file '../config.rpath' not found"

### ISSUE THREAD

**Issue by peshoicov** [dlenski/openconnect#37]
I was getting this error until a while ago:

```
# ./autogen.sh 
autoheader: warning: missing template: LIBPROXY_HDR
autoheader: Use AC_DEFINE([LIBPROXY_HDR], [], [Description])
```

After installing `pkg-config` now I'm getting this:

```
# ./autogen.sh 
configure.ac:202: error: required file '../config.rpath' not found
```

I wonder why is it looking at this in the parent directory, this file is already there??

I'm on Debian 8, kernel 4.9 (this kernel I installed specifically because I thought this is the reason for that I'm unable to build this package).

**Comment by dlenski** [comment]
> I'm on Debian 8, kernel 4.9 (this kernel I installed specifically because I thought this is the reason for that I'm unable to build this package).

Do you have `libproxy-dev` installed as shown in [the Linux build instructions](https://github.com/dlenski/openconnect#building-from-source-on-linux)?

**Comment by dlenski** [comment]
> After installing pkg-config now I'm getting this:
>
> ```
> # ./autogen.sh 
> configure.ac:202: error: required file '../config.rpath' not found
> ```
> I wonder why is it looking at this in the parent directory, this file is already there??

Honestly, I don't know the GNU autotools very well myself… but it may be related to this bug. https://lists.gnu.org/archive/html/bug-gettext/2011-10/msg00012.html

Can you run 'git clean -fx && git reset --hard' to reset the directory contents to the pristine version, and try again?

**Comment by peshoicov** [comment]
Yes, I hade `libproxy-dev` installed.
But before I tried the other commands I deleted all folders and checked-out everything from scratch, and all went fine.

THEN I saw that I had cloned the repo to a folder named openconnect, and that it was inside another folder with all the files. Like two folders one inside the other. And I was trying to build from the inner one.
Aaand ... my guess is that this was causing the issue :D ... 

(Just tried to reproduce the issue but I couldn't ... however - my guess is that this was the cause ...)

Cheers :beer:

**Comment by Yoshimit** [comment]
I'm having this same problem with my Mint 18.
All dependencies installed.
Unlike peshoicov, I dont have two folders with all data.
Git reset --hard did not solve.

After ./autogen.sh I got these messages:

```
configure.ac:121: installing '../../compile'
configure.ac:210: error: required file '../../config.rpath' not found
configure.ac:8: installing '../../missing'
Makefile.am: installing '../../depcomp'
```

Any hint, please?

**Comment by dlenski** [comment]
> I don't have two folders with all data.

What does this mean?

**Comment by Yoshimit** [comment]
Sorry for that.

@peshoicov said:
> [...] and that it was inside another folder with all the files.[...]

I meant that I don't have that. Only one folder with files from git as should be.
I'm without options here and seem your code is the only one that supports protocol gp, so I need to try it out.

**Comment by jusondac** [comment]
so, what the solution?

**Comment by jmagb** [comment]
Ey guys, the solution is to add the description argument when defining the LIBPROXY_HDR library. So if you've got:
`AC_DEFINE([LIBPROXY_HDR], ["proxy.h"])` 

You need to change it to:
`AC_DEFINE([LIBPROXY_HDR], ["proxy.h"], [libproxy header file])`

This is at lines 729 and 735 of file configure.ac

See you!
