### ISSUE TITLE
Can not make it work

### ISSUE THREAD

**Issue by caneraydinbey** [dlenski/openconnect#38]
# Problem description

1. I ran openconnect-gp as follows:
```➜  openconnect git:(globalprotect) ✗ ./autogen.sh                   
configure.ac:113: installing './compile'
configure.ac:8: installing './missing'
Makefile.am: installing './depcomp'
```
2. 
3.
4.

# Operating system and openconnect-gp version
ubuntu 17.04
openconnect-gp version:

```
    <!-- Run "openconnect --version" and include the output here -->

➜  openconnect git:(globalprotect) ✗ openconnect --version
OpenConnect version v7.08
Using GnuTLS. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS

```

operating system

```
    <!-- Run "uname -a" and include the output here -->➜  openconnect git:(globalprotect) ✗ uname -a
Linux caner 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

# GlobalProtect VPN information

```
<!--
    Run openconnect with the highest verbosity, and dump all HTTP traffic:
    
       openconnect --dump-http-traffic -vvvv 
       
    Compare its output with the anonymized GlobalProtect VPN connection flow shown here:
    
       https://gist.github.com/dlenski/5046e5f934ac111e8d8718fc10c25703

    Include as much of the HTTP traffic as you can here. Don't forget to anonymize sensitive
    information, especially:
       - username
       - password
       - authcookie
       - ESP keys
       - external IP addresses
-->
```

it gives error 

```
➜  openconnect git:(globalprotect) ✗ ./autogen.sh                   
configure.ac:113: installing './compile'
configure.ac:8: installing './missing'
Makefile.am: installing './depcomp'



then



`➜  openconnect git:(globalprotect) ✗ ./configure                    
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
configure: Applying feature macros for GNU build
configure: error: /etc/vpnc/vpnc-script does not seem to be executable.
 OpenConnect will not function correctly without a vpnc-script.
 See http://www.infradead.org/openconnect/vpnc-script.html for more details.

 If you are building a distribution package, please ensure that your
 packaging is correct, and that a vpnc-script will be installed when the
 user installs your package. You should provide a --with-vpnc-script=
 argument to this configure script, giving the full path where the script
 will be installed.

 The standard location is /etc/vpnc/vpnc-script. To bypass this error and
 build OpenConnect to use the script from this location, even though it is
 not present at the time you are building OpenConnect, pass the argument
 "--with-vpnc-script=/etc/vpnc/vpnc-script"
```

I followed the guide

**Comment by dlenski** [comment]
The explanation for how to fix this is right there in the error message.

Under Ubuntu, the vpnc-script is installed in a different location so you need to run…

```
./configure --with-vpnc-script=/usr/share/vpnc-scripts/vpnc-script
```

**Comment by caneraydinbey** [comment]
`➜  openconnect git:(globalprotect) ✗ git checkout globalprotect
Already on 'globalprotect'
Your branch is up-to-date with 'origin/globalprotect'.
➜  openconnect git:(globalprotect) ✗ ./autogen.sh 
configure.ac:113: installing './compile'
configure.ac:8: installing './missing'
Makefile.am: installing './depcomp'
➜  openconnect git:(globalprotect) ✗ ./configure --with-vpnc-script=/usr/share/vpnc-scripts/vpnc-script
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
configure: Applying feature macros for GNU build
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for fdevname_r... no
checking for statfs... yes
checking for getline... yes
checking for strcasestr... yes
checking for strndup... yes
checking for asprintf... yes
checking for vasprintf... yes
checking for supported compiler flags...  -Wall -Wextra -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-parameter -Werror=pointer-to-int-cast -Wdeclaration-after-statement -Werror-implicit-function-declaration -Wformat-nonliteral -Wformat-security -Winit-self -Wmissing-declarations -Wmissing-include-dirs -Wnested-externs -Wpointer-arith -Wwrite-strings
checking for socket... yes
checking for inet_aton... yes
checking for IPV6_PATHMTU socket option... yes
checking for __android_log_vprint... no
checking for __android_log_vprint in -llog... no
checking for nl_langinfo... yes
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for msgfmt... /usr/bin/msgfmt
checking for functional NLS support... yes
checking for GNUTLS... no
checking for OPENSSL... yes
checking for P11KIT... no
checking for known-broken versions of OpenSSL... yes
configure: error: This version of OpenSSL is known to be broken with Cisco DTLS.
See http://rt.openssl.org/Ticket/Display.html?id=4631&user=guest&pass=guest
Add --without-openssl-version-check to configure args to avoid this check, or
perhaps consider building with GnuTLS instead.
➜  openconnect git:(globalprotect) ✗ make
make: *** No targets specified and no makefile found.  Stop.
`

it did not work also @dlenski

**Comment by dlenski** [comment]
Again, read the output and consider what it is telling you.
