### ISSUE TITLE
Advice/Instructions For Upgrading From A Linux Source Install

### ISSUE THREAD

**Issue by jonesbf** [dlenski/openconnect#39]
# Problem description

1. I have a successful, operating version of your package that I built from source using the directions titled "Building from source on Linux"
2. I'd like to upgrade to the latest version, but am a little perplexed as to what is the best route to go about doing this.
3.  Dan, how do you normally go about upgrading it with minimal issues?  My source-installed OpenConnect wtih GP mod is installed in `\usr\local\openconnect`
4.  I think I'm fine making a new install file on my own.  I just don't know about the proper/thorough way to upgrade from old to new. Thanks

**Comment by dlenski** [comment]
If I'm understanding you correctly… you built openconnect-gp once, from source, and installed to `/usr/local`:

```sh
$ git clone https://github.com/dlenski/openconnect
$ cd openconnect
$ ./configure --prefix=/usr/local
$ make
$ sudo make install
```

… and now you want to install an updated build?

You should be able to simply redo the `configure`, `make` and `sudo make install` steps.

If you want to be extra careful, run `sudo make uninstall` in the source directory before doing this, but it's probably unnecessary (and many Makefiles are fairly sloppy or rudimentary in their "uninstall" capabilities, anyway).

**Comment by dlenski** [comment]
OpenConnect doesn't have any global config files, so there's nothing to worry about there.

**Comment by jonesbf** [comment]
Awesome, thanks again!
