### ISSUE TITLE
Client certificate authentication

### ISSUE THREAD

**Issue by Zjemm** [dlenski/openconnect#4]
Hi,

i'm running on PANOS 7.1.5 and i cant seem to get openconnect to work with client certificate auth enabled.

i'm allways getting:
Got HTTP response: HTTP/1.1 513 Custom error
Unexpected 513 result from server
Invalid client certificate.
Failed to obtain WebVPN cookie

i created a selfsigned CA on the PAN, and used that in the certificate profile.
then i created a certificate signed by the CA i just created and exported it with the key. to a pem file

i'm not sure if this version is supported with PANOS 7.1.5 an GP version 3.1.3

without the certificate auth it works just fine.

NOTE: This is really a great peace of software you created.... i was using vpnc, but as i'm on different client-sites, not always the ports required to connect with vpnc are open. and 443 is, so that is a lot better

**Comment by dlenski** [comment]
@zjemm, I think this is an issue with your *server-side* configuration. I am using a client certificate with no problems.

(I know nothing at all about the server side of  GlobalProtect.)

If you run `openconnect --dump -vvvv`, you'll get a ton of debugging output that may shed some light on what's going on.

**Comment by Zjemm** [comment]
I Will try that. And also dorst try the certificate on a Windows box

Might indeed be en config error on the server side

**Comment by dlenski** [comment]
Okay. The exchange of the client/server certificates, as used by GlobalProtect, is an _entirely_ standard part of TLS.

Let us know what you find.

**Comment by Zjemm** [comment]
so its working now.

in the certificate profile i had some options check to block the session if the certificate status is unknown e.t.c.

probably because i use the self signed certificate this is this issue.

now lets see if i can run it in the background

**Comment by dlenski** [comment]
> run it in the background

`-b`

**Comment by Zjemm** [comment]
nice, do you also know how to properly discconnect?
what do you use for that?

**Comment by dlenski** [comment]
> nice, do you also know how to properly discconnect?

The [openconnect man page](http://infradead.org/openconnect/manual.html) clearly explains that certain signals cause immediate disconnect, while others cause a "clean" disconnect with logoff.

This version obeys that.
