### ISSUE TITLE
Signature Verification failed in PPA

### ISSUE THREAD

**Issue by dshahrokhian** [dlenski/openconnect#42]
I followed the installation instructions under the [PPA](https://launchpad.net/~lenski/+archive/ubuntu/openconnect-gp): 
`sudo add-apt-repository ppa:lenski/openconnect-gp
sudo apt-get update`

But then I have the following warnings: 

`W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04  Release: The following signatures were invalid: KEYEXPIRED 1496576244
W: Failed to fetch http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/Release.gpg  The following signatures were invalid: KEYEXPIRED 1496576244
W: Some index files failed to download. They have been ignored, or old ones used instead.
`

I try running the command:
`openconnect --protocol=gp \                                                    
              <site address> --dump -vvv`
but it doesn't even recognize it.

**Comment by dlenski** [comment]
Hmmm… I don't know why the signature validation would fail. No idea there.

Also, I have not updated the Debian/Ubuntu package in quite a while and it is now out of date. I haven't had time to streamline the packaging process yet.

I recommend that you build and install openconnect-gp from the source code checked out from Git. It will take a little longer, but you'll get the latest version, which has had a lot of bug fixes and configuration improvements.

**Comment by hyperair** [comment]
> http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04 Release

Doesn't look like the PPA URL. Perhaps you've got another broken repo in your apt sources?

**Comment by dshahrokhian** [comment]
(Sorry for the late reply)

@dlenski I will try that within this week, thanks.

@hyperair I am not sure if I understand your comment. The url I provided isn't that one you describe, but this https://launchpad.net/~lenski/+archive/ubuntu/openconnect-gp. It is explicitly referenced in the installation instruction of the README.

**Comment by dlenski** [comment]
I haven't updated the PPA in a while… sorry. It's difficult for me to build the .deb packages, and by now they're far behind the Git repository.

The whole GlobalProtect support should be merged upstream soon, and then hopefully it'll get rolled out to everyone's favorite distro packages soon :+1:
