### ISSUE TITLE
Slow upload performance due to PMTU firewall blocking

### ISSUE THREAD

**Issue by rbeede** [dlenski/openconnect#43]
Upload speed is very slow compared to using the OEM Windows client.  Turns out a firewall (same net as gateway) blocks all ICMP packets to the gateway which makes PMTU discovery impossible.

This results in a slow upload speed as the MTU used is too low.

1. I ran openconnect-gp as follows: `sudo ./openconnect --protocol=gp --script /usr/share/vpnc-scripts/vpnc-script 000.000.000.000` (gateway IPv4 address sensored)

# Operating system and openconnect-gp version

openconnect-gp version:

```
OpenConnect version v7.08-152-g7a420ca
Using OpenSSL. Features present: TPM (OpenSSL ENGINE not present), HOTP software token, TOTP software token, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp

```

operating system

```
$ uname -a
Linux rbeede 4.8.0-58-generic #63-Ubuntu SMP Mon Jun 26 17:08:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.10"
VERSION_ID="16.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="http://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=yakkety
UBUNTU_CODENAME=yakkety

```

# GlobalProtect VPN information

```
Using RSA token login.

Say "yes" to accepting self-signed certificate.

Main issue is that ICMP packets are blocked by firewall so they don't reach VPN-gateway.
```

# Other useful info

Gigabit Fiber (AT&T) home connection to vpn-gateway hosted on AT&T business connection in same city.

Used wired connection from client system on local home network to connect.

**Comment by rbeede** [comment]
Workaround for those with gigabit fiber home connections is:

**--mtu=5200**

```
sudo ./openconnect --mtu=5200 --protocol=gp --script /usr/share/vpnc-scripts/vpnc-script  1.2.3.4
```

**Comment by dlenski** [comment]
Hi @rbeede, this is a very interesting finding. The `--mtu` option only sets the MTU of the virtual tunnel interface, and should not affect the size of the packets actually sent to/from the external gateway.

Some questions:

* What does `ip addr` show for the MTU of your "real" network device?
* Does your GP gateway support ESP, or only HTTPS/SSL?
* Do you understand how the Windows client figures out the MTU, both the client-to-gateway PMTU and the VPN internal MTU (which is what `--mtu` sets)?

The GP gateway always sends a value of zero for the MTU in its XML configuration, forcing me/openconnect to *guess* a correct value of the MTU for the tunnel device. It would be great to have a smarter way to negotiate MTU.

**Comment by rbeede** [comment]
`3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 12:34:56:78:90:ab brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.9/24 brd 192.168.0.255 scope global dynamic wlp3s0
       valid_lft 86224sec preferred_lft 86224sec
    inet6 fe80::1234:5678:90ab:cdef/64 scope link 
       valid_lft forever preferred_lft forever
`

`6: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 5200 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 10.1.2.9/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::aeb3:1234:1234:1234/64 scope link flags 800 
       valid_lft forever preferred_lft forever
`

**Comment by rbeede** [comment]
`
Username: rbeede
Password: 
POST https://172.16.1.2/ssl-vpn/login.esp
Connected to 172.16.1.2:443
SSL negotiation with 172.16.1.2
Server certificate verify failed: self signed certificate in certificate chain

Certificate from VPN server "172.16.1.2" failed verification.
Reason: self signed certificate in certificate chain
To trust this server in future, perhaps add this to your command line:
    --servercert sha256:abcdef1234567890abcdef1234567890abcdef1234567890
Enter 'yes' to accept, 'no' to abort; anything else to view: yes
Connected to HTTPS on 172.16.1.2
POST https://172.16.1.2/ssl-vpn/login.esp
GlobalProtect login returned authentication-source=MyOrg Radius Auth
POST https://172.16.1.2/ssl-vpn/getconfig.esp
No MTU received. Calculated 5200
Connected as 10.1.2.9, using SSL
ESP session established with server
ESP tunnel connected; exiting HTTPS mainloop.
`

**Comment by rbeede** [comment]
I'm not sure on details.   I can spin-up a VM with Windows and a client, but what would I need to capture?   Wireshark packets?


One possibility would be to send do not fragment TCP packets on port 443 to the provided gateway.   Choose a sane initial default and ramp up or down until the packets get dropped.

So perhaps start at 1410, increase to 2820, etc.    If 1410 didn't make it then go down by 50% until you reach the bottom possible value.

This would avoid ICMP firewall blocking and give a decent guess of a usable MTU.

**Comment by dlenski** [comment]
Sorry, I lost track of this thread for a while.

I don't really understand what's going on with your VPN. According to your `ip addr` output, the MTU of the real network device (`wlan0`) is only 1500, so I don't understand how an MTU of 5200 can be optimal for the tunnel device.

This means that the ESP-wrapped IPv4 packets sent to the tunnel gateway will be _constantly_  getting [fragmented](https://en.wikipedia.org/wiki/IP_fragmentation) by your local system, and then reassembled by the gateway. So I just don't see how that behavior can actually be optimal for the upload performance, unless there's something else which is limiting the network speed even more.

**Comment by rbeede** [comment]
Using the manual mtu setting is a solution for me.

**Comment by dlenski** [comment]
> AIUI the MTU setting only affects the packets from client to server — the server just does its own thing anyway, right?

Right. The GlobalProtect server gives absolutely no indication of the largest packet it might send to the client. :angry:
