### ISSUE TITLE
Error making package

### ISSUE THREAD

**Issue by mmazon** [dlenski/openconnect#45]
Trying to **make** package openconnect, all dependencies and libs were installed successfully

**1. When I ran the make command:** 
cstp.c: In function 'start_cstp_connection':
cstp.c:219:6: warning: unused variable 'dtls_secret_set' [-Wunused-variable]
  int dtls_secret_set = 0;
      ^
  CC       libopenconnect_la-oath.lo
  CC       libopenconnect_la-gpst.lo
gpst.c:331:12: warning: 'set_esp_algo' defined but not used [-Wunused-function]
 static int set_esp_algo(struct openconnect_info *vpninfo, const char *s, int hmac)
            ^
gpst.c:345:12: warning: 'get_key_bits' defined but not used [-Wunused-function]
 static int get_key_bits(xmlNode *xml_node, unsigned char *dest)
            ^
  CC       libopenconnect_la-auth-globalprotect.lo
  CC       libopenconnect_la-gnutls.lo
gnutls.c: In function '_openconnect_gnutls_read':
gnutls.c:201:16: error: 'GNUTLS_E_TIMEDOUT' undeclared (first use in this function)
    if (done == GNUTLS_E_TIMEDOUT) {
                ^
gnutls.c:201:16: note: each undeclared identifier is reported only once for each function it appears in
gnutls.c: At top level:
gnutls.c:2580:15: error: conflicting types for 'gnutls_ext_send_func'
 typedef int (*gnutls_ext_send_func) (gnutls_session_t session,
               ^
In file included from gnutls.c:36:0:
/usr/include/gnutls/gnutls.h:806:17: note: previous declaration of 'gnutls_ext_send_func' was here
   typedef int (*gnutls_ext_send_func) (gnutls_session_t session,
                 ^
make[1]: *** [libopenconnect_la-gnutls.lo] Error 1
make[1]: Leaving directory `/home/mazon/openconnect'
make: *** [all] Error 2

Using ubuntu 14.04

**Comment by dlenski** [comment]
```
gnutls.c:201:16: error: 'GNUTLS_E_TIMEDOUT' undeclared (first use in this function)
```

Hmmm… you must be using a very old version of the GnuTLS libs. I've built successfully on Ubuntu 14.04. The naming of GnuTLS package versions on Ubuntu is very confusing (see [this thread on the official OC mailing list](http://lists.infradead.org/pipermail/openconnect-devel/2017-May/004354.html)), but what you need to install is [libgnutls28-dev](https://packages.ubuntu.com/trusty/libgnutls28-dev) which is actually GnuTLS 3.2.11.

Don't blame me… I didn't name 'em. ¯\\\_(ツ)\_/¯

**Comment by mmazon** [comment]
Thanks @dlenski 
It worked smoothly huhuhu \o/
