### ISSUE TITLE
Dynamic linking problem

### ISSUE THREAD

**Issue by kozzztik** [dlenski/openconnect#56]
# Problem description

1. Build lib from sources as said in readme
2. I ran openconnect-gp as follows: `openconnect --version

# Operating system and openconnect-gp version

openconnect-gp version: build from repo.
un
operating system
Linux debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

And it gives error:

```
openconnect: error while loading shared libraries: libopenconnect.so.5: cannot open shared object file: No such file or directory
```

I do:

```
ldd /usr/local/sbin/openconnect 
	linux-vdso.so.1 (0x00007ffd3c7ad000)
	libopenconnect.so.5 => not found
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fb8012d8000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fb800f1d000)
	libproxy.so.1 => /usr/lib/x86_64-linux-gnu/libproxy.so.1 (0x00007fb800cfc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb80095d000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb800741000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fb8004dc000)
	libidn.so.11 => /lib/x86_64-linux-gnu/libidn.so.11 (0x00007fb8002a8000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fb800095000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007fb7ffe5e000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007fb7ffc29000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fb7ff9a4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb7ff7a0000)
	libicui18n.so.57 => /usr/lib/x86_64-linux-gnu/libicui18n.so.57 (0x00007fb7ff326000)
	libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57 (0x00007fb7fef7e000)
	libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57 (0x00007fb7fd501000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fb7fd2db000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb7fcfd5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb7fcdb8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb7fca36000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb7fc81f000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559de7985000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fb7fc616000)
```

simply running ldconfig solves problem. I don`t finally sure where is problem but ldd have old cache for some reason during installation.

**Comment by dlenski** [comment]
> simply running ldconfig solves problem. I don`t finally sure where is problem but ldd have old cache for some reason during installation.

Hmmm. I haven't run into this on any other distro. This isn't specific to openconnect-gp… the official openconnect build should suffer from it as well.

Perhaps you should mention it on the official mailing list and see if anyone else is having this problem? Maybe `ldconfig` should be added to the end of `make install`.

**Comment by plasx** [comment]
I bumped into this issue, for me my LD_LIBRARY_PATH variable was not declared, I had to type the following in terminal to get it to work:
`export LD_LIBRARY_PATH=/usr/local/lib`
Might want to put that in your ~/.bashrc if you want it to be there when you login to terminal the next time.

**Comment by fedek6** [comment]
This solution also worked for me on Elementary OS. Simply use sudo ldconfig after make install.

**Comment by dan-viziapps** [comment]
Ubuntu 18.04.3 LTS fixed the error 'sudo ldconfig'
