### ISSUE TITLE
2 factor authentication failure

### ISSUE THREAD

**Issue by red-lonely-neuron** [dlenski/openconnect#57]
# Problem description

I have attempted to connect to my company's VPN using the following command: `sudo openconnect --protocol=gp -U myhostuser -u myuser vpn.abcdef.com`
My company uses a 2 factor authentication method and after giving my password, openconnect exits without waiting for me to choose the way to check in the second phase. Could you, please suggest a way to make openconnect wait for me to input the check mode?

# Operating system and openconnect-gp version

openconnect-gp version:

```
    OpenConnect version v7.08-1ubuntu5
Using GnuTLS. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS
```

operating system

```
    Linux tasmania 4.11.0-14-generic #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

# GlobalProtect VPN information

```
POST https://vpn.abcdef.com/ssl-vpn/login.esp
Attempting to connect to server 1.2.3.4:443
Connected to 1.2.3.4:443
SSL negotiation with vpn.abcdef.com
Connected to HTTPS on vpn.abcdef.com
> POST /ssl-vpn/login.esp HTTP/1.1
> Host: vpn.abcdef.com
> User-Agent: PAN GlobalProtect
> X-Pad: 0000000000000000000000000000000000000000000000000
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 143
> 
> jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:&server=vpn.abcdef.com&computer=tasmania&user=myuser&passwd=mypasswd
Got HTTP response: HTTP/1.1 200 OK
Server: 
Date: Wed, 11 Oct 2017 17:21:08 GMT
Content-Type: text/html
Content-Length: 224
Connection: keep-alive
ETag: "ttttt-1e54-xxxxxxxx"
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-FRAME-OPTIONS: DENY
Set-Cookie: PHPSESSID=f7944c3a6ea3496a277427154f319277; secure; HttpOnly
Set-Cookie: PHPSESSID=f7944c3a6ea3496a277427154f319277; secure; HttpOnly
Set-Cookie: PHPSESSID=f7944c3a6ea3496a277427154f319277; secure; HttpOnly
HTTP body length:  (224)
< 
< var respStatus = "Challenge";
< var respMsg = "Please select your second authentication method [num]:  1 - Okta Verify. 2 - Okta Verify Push. 3 - SMS Authentication. Enter '0' to abort. ";
< thisForm.inputStr.value = "70dbf";
< 
```

**Comment by dlenski** [comment]
Are you using the ancient version from the Ubuntu PPA? If so… build from source and use that.

I added 2FA support around February (starting with 6951a167e60d1f9d3bcb4f3d80677a85d09f7ba4).

**Comment by red-lonely-neuron** [comment]
Hi. Thank you for your answer. Yes, the deb package contains an older version (January 10th, 2017). I preferred the package way because the package manager keeps track of the installed files and, in case I wanted a newer version or to uninstall, it doesn't leave any garbage. I'll build from sources and try those binaries then.

**Comment by dlenski** [comment]
> I'll build from sources and try those binaries then.

Let me know if this works.

**Comment by red-lonely-neuron** [comment]
I have built and tested the tool and it worked fine. Thank you. Your code being included in the official OpenConnect is great news.
