### ISSUE TITLE
Can't install from PPA on Ubuntu 17.04

### ISSUE THREAD

**Issue by github-t** [dlenski/openconnect#58]
When I run a "sudo apt update" I get:

_E: The repository 'http://ppa.launchpad.net/lenski/openconnect-gp/ubuntu zesty Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details._

I am able to build from source and run without issue.  Having the PPA working would help the lazy out there :).

**Comment by dlenski** [comment]
I am not maintaining the PPA anymore. It's a lot more work than it looks like, and the GP support will get merged into the official OpenConnect soon, then picked up by distribution packaging experts I hope.

**Comment by github-t** [comment]
Ah ok sorry didn't know. And that's great to hear it'll be merged in. Thanks for all of your work!
