### ISSUE TITLE
Issues with autogen.sh

### ISSUE THREAD

**Issue by popsandthefamily** [dlenski/openconnect#59]
# Problem description

Ran autogen.sh and received the following error:

configure.ac:120: installing './compile'
configure.ac:8: installing './missing'
Makefile.am: installing './depcomp'

As a result the next steps with the make file do not work.

# Operating system and openconnect-gp version

openconnect-gp version: latest
OS: Fedora 27

**Comment by dlenski** [comment]
I don't know anything about Fedora. Do you have whatever the typical packages are for building autotools-based programs?

**Comment by popsandthefamily** [comment]
Yes I have downloaded all pre-requisites.

I had this working last week but had to wipe my box and lost the ability to
compile and run it.

**Comment by dlenski** [comment]
What are "all pre-requisites"? Your problem description doesn't give enough information to help address it.
