### ISSUE TITLE
--no-cert-check

### ISSUE THREAD

**Issue by matti157** [dlenski/openconnect#6]
Hi,
I need to connect to a VPN of my customer, his server certificate is not valid (expired or self generated...I don't know....but globalprotect client in windows client works).
But I need to connect anyway even if there are security problems.

Now the vpn connects but no traffic is generated

I think that the deprecated command parameter --no-cert-check would works in my case

I can not ask my customer IT to fix the certificate.

Attached the screen

![schermata 2016-12-16 alle 17 48 37](https://cloud.githubusercontent.com/assets/3799465/21270766/4dbb6fdc-c3b8-11e6-971e-2573e7a24a7b.png)

**Comment by dlenski** [comment]
No, this doesn't appear to be a problem with the SSL certificate; `openconnect` would simply refuse to connect if it didn't trust the certificate fingerprint, and you're overriding it with `--fingerprint` so that should work.

Please run with `-vvvv` to produce a ton of debugging output. What does it show?

**Comment by matti157** [comment]
Hi,
thank you for the fast response!

Attached the complete log with --no-dtls option.

[VPNLog.txt](https://github.com/dlenski/openconnect/files/660713/VPNLog.txt)

**Comment by dlenski** [comment]
@matti157, This log doesn't make any sense to me:

1. The connection setup is getting stuck in an infinite loop.
2. It is trying to setup the ESP connection (which *should be disabled* with `--no-dtls`).

Does your command line look exactly like this, or is there something else in it?

```
$ sudo openconnect --protocol=gp GATEWAY --servercert sha1:HASH --no-dtls -vvvv
```

And, can you tell me exactly what version you built? `git describe --always` should show the exact hash.

**Comment by dlenski** [comment]
Do you have any further updates on this? Did you get it working?

**Comment by matti157** [comment]
Hi,
sorry for the delayed response but I was on holidays.
The command is correct
My version is 7.06-2ubuntu1 installed from Lubuntu package manager

**Comment by dlenski** [comment]
How did you set up the Lubuntu package manager to use this version?
Did you point it at my PPA repository? (https://launchpad.net/~lenski/+archive/ubuntu/openconnect-gp)

**Comment by matti157** [comment]
No, I got it from the default repository. I try to download it from your

**Comment by matti157** [comment]
![schermata 2017-01-04 alle 09 20 43](https://cloud.githubusercontent.com/assets/3799465/21635794/f81d8b26-d25f-11e6-8d26-5ad4959f4dd5.png)

**Comment by dlenski** [comment]
It appears that your server always disconnects immediately after sending the VPN configuration, before the tunnel setup. This is a bit mystifying… I haven't seen this behavior before.

Can you try a "two-pass" connection, in which you do the authentication in one connection, and then the tunnel setup in the second connection?

1. ```sh
$ openconnect --protocol=gp vpn.xxx.it --servercert sha1:whatever 
COOKIE='authcookie=AUTHCOOKIE&portal=PORTAL&user=USERNAME&domain=DOMAIN'
HOST='123.45.67.89'
FINGERPRINT='sha1:whatever'

$ <set the variables above>

$ openconnect --protocol=gp --servercert "$FINGERPRINT" --cookie "$COOKIE" "$HOST" --no-dtls
```

**Comment by matti157** [comment]
thanks!
how do I get the output from the first command?

**Comment by dlenski** [comment]
> thanks!
> how do I get the output from the first command?

Derp… I forgot to include the `--authenticate` flag, which causes it to stop and show the output.

(you should also [read the manual and understand how this works](www.infradead.org/openconnect/manual.html))

**Comment by dlenski** [comment]
Not sure if you're still having this problem, but I pushed a newer package to the Ubuntu repository, which includes b0e7568983ccd021015f84725fa41c0cb8976a8c.

This has fixed several other users' problems where they can connect but can't send any traffic.
