### ISSUE TITLE
Compile problem on Mac OS Sierra

### ISSUE THREAD

**Issue by ricardo85x** [dlenski/openconnect#64]
# Problem description

I install openconnect with brew and run in that way
`openconnect --protocol=gp vpn.acme.com --dump -vvv`

But got this message:
`Unknown VPN protocol 'gp'`

And when I try to compile with this command:

`./configure --prefix=/usr/local --with-vpnc-script=/usr/local/etc/vpnc-script --disable-nls --without-gnutls`

or this

`./configure --prefix=/usr/local --with-vpnc-script=/usr/local/etc/vpnc-script --disable-nls`

I got this message:

`checking for known-broken versions of OpenSSL... yes
configure: error: LibreSSL does not support Cisco DTLS.
Build with OpenSSL or GnuTLS instead.`

**Comment by dlenski** [comment]
I don't use MacOS, but MacOS build instructions were contributed by another user and are [right there in the README](https://github.com/dlenski/openconnect#building-on-the-mac).

**Comment by dlenski** [comment]
I don't use MacOS, but MacOS build instructions were contributed by another user and are [right there in the README](https://github.com/dlenski/openconnect#building-on-the-mac).

**Comment by dlenski** [comment]
I don't use MacOS, but MacOS build instructions were contributed by another user and are [right there in the README](https://github.com/dlenski/openconnect#building-on-the-mac).

**Comment by dlenski** [comment]
I don't use MacOS, but MacOS build instructions were contributed by another user and are [right there in the README](https://github.com/dlenski/openconnect#building-on-the-mac).

**Comment by ricardo85x** [comment]
I did follow both instruction and I have this problem.
When I install with homebrew only. It do not have the "gp" protocol.
And when I try to compile it, I got this error
`ibreSSL does not support Cisco DTLS. Build with OpenSSL or GnuTLS instead.`

on the history I saw Robert did add the info on how to compile, but look like he is not on GitHub anymore...
https://github.com/dlenski/openconnect/commit/bec24106f773267089c7afe977a82c3b91e08112#diff-04c6e90faac2675aa89e2176d2eec7d8

I fond this closed ticket https://github.com/dlenski/openconnect/pull/10  with the same problem:

**Comment by dlenski** [comment]
Installing openconnect with homebrew *does not* install *this* version of openconnect; it installs from the official mainline which has not yet merged my GlobalProtect support.

Did you try explicitly adding `--with-gnutls` to the `configure` options?

#10 was merged: that's _where_ the MacOS build instructions got added.

#34 seems related as well, and I should reemphasize what I wrote there: this version of openconnect is *identical* to the mainline openconnect v7.08 in its build requirements. It has no new dependencies. If you can't build the mainline, you should ask for help on the official mailing list.

**Comment by ricardo85x** [comment]
I was able to compile and run.
But I did have to to some workarounds.


```
$ brew install pkg-config gettext gnutls lz4  libxslt libxml2
$ export LIBTOOLIZE=glibtoolize
$ ./autogen.sh
# edit the configure file and add this 2 lines before # First, check if GnuTLS exists and is usable:
GNUTLS_LIBS='-L/usr/local/Cellar/gnutls/3.5.8/lib -lgnutls  '
GNUTLS_CFLAGS='-I/usr/local/Cellar/gnutls/3.5.8/include -I/usr/local/Cellar/libtasn1/4.12/include   -DXMLSEC_CRYPTO_GNUTLS=1'
# comment this two lines :
#  #GNUTLS_CFLAGS=$pkg_cv_GNUTLS_CFLAGS
#  #GNUTLS_LIBS=$pkg_cv_GNUTLS_LIBS 
# replace this line:
	else
	    ssl_library=GnuTLS
	fi
# with this:
	else
	    ssl_library=GnuTLS
	fi
	ssl_library=GnuTLS
# configure with:
$ ./configure --prefix=/usr/local --with-vpnc-script=/usr/local/etc/vpnc-script --disable-nls --with-gnutls --with-libxml=/usr/local/Cellar/libxml2/2.9.7

$ make
$ make install
```

Probably there is a better way to do it. But it will work.

Thanks for this modified version of openconnect!

**Comment by dlenski** [comment]
Hmm. It seems that the configure script didn't correctly autodetect GnuTLS?

Did you try explicitly adding `--with-gnutls` to the configure command-line options, as I suggested above? Did it still not work, without your modifications?

**Comment by ricardo85x** [comment]
Yes I did.
The final configure command is that:
`$ ./configure --prefix=/usr/local --with-vpnc-script=/usr/local/etc/vpnc-script --disable-nls --with-gnutls --with-libxml=/usr/local/Cellar/libxml2/2.9.7
`

**Comment by dlenski** [comment]
Does it work if you used `--with-gnutls=/usr/local/Cellar/gnutls/` instead?

If not, please report on [the OpenConnect mailing list](http://www.infradead.org/openconnect/mail.html)! If it doesn't build correctly on MacOS with brew, this will affect all versions of OpenConnect, since nothing about the build process here is different for my GP-supporting version.

**Comment by ricardo85x** [comment]
I will report.

the with-gnutls only support yes or no.
`configure: error: Values other than 'yes' or 'no' for --with-gnutls are not supported`
