### ISSUE TITLE
Paths with spaces

### ISSUE THREAD

**Issue by rmonascal** [dlenski/openconnect#66]
While installing the project I had an issue while executing `make`. After reading the files I noticed there are some variables set in the configuration script that don't add the string delimiters for paths that contain spaces. After deleting spaces in my working directory's path, installation was smooth and successful.

**Comment by dlenski** [comment]
Thanks. If you can create a patch for this, please submit it to [the official openconnect mailing list](http://www.infradead.org/openconnect/mail.html), since the build process for this version is identical to the official one.
