### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by rmonascal** [dlenski/openconnect#67]
My VPN connection works with two factor authentication: First an initial password is given, then a combination of a personal PIN and a time-sensitive authentication token must be supplied. Neither my password or the PIN+Token combination were accepted by `openconnection`. Support for this type of authentication would be great. Thanks!

**Comment by dlenski** [comment]
I added support for challenge-based 2FA months ago and have many reports of it working successfully from other users.

Please submit all the logs and details of exactly which build you're running and how it fails, as specified in the issue report template.

**Comment by KriCG** [comment]
@dlenski What is the command for openconnect to connect with two factor authentication ?
