### ISSUE TITLE
failure to reconnect/renew tokens

### ISSUE THREAD

**Issue by senecaso-sf** [dlenski/openconnect#73]
# Problem description

after running the VPN for several hours, I always get the same error message and the tunnel is closed.  I then need to manually reconnect

1. I run openconnect-gp as follows:
```sh
cat "$HOME/.secrets/vpn.passwd" |
    sudo openconnect --protocol=gp vpn.example.com --user="my.user" --background \
         --pid-file=/var/run/vpn.pid --script "vpn-slice ${SUBNETS[*]} ${HOSTS[*]}" \
         2>&1 > /var/log/vpn.log
```

2. after 2-3hrs, I always get the following messages displayed and the tunnel terminates: 
```
SSL read error: The TLS connection was non-properly terminated.; reconnecting.
Packet receive error: Input/output error
Invalid authentication cookie
Invalid authentication cookie
Invalid authentication cookie
Invalid authentication cookie
Invalid authentication cookie
Invalid authentication cookie
Failed to read from SSL socket: The TLS connection was non-properly terminated.
Error fetching HTTPS response
Got inappropriate HTTP GET-tunnel response: HTTP/1.1 502 Bad Gateway
Invalid authentication cookie
Failed to read from SSL socket: The TLS connection was non-properly terminated.
Error fetching HTTPS response
Got inappropriate HTTP GET-tunnel response: HTTP/1.1 502 Bad Gateway
Reconnect failed
Invalid user name
Logout failed.
WARNING: CISCO_SPLIT_* environment variables set, but this version of vpn-slice does not handle them
Unknown error; exiting.
```

3. I need to manually reconnect to re-establish connection: goto 1

# Operating system and openconnect-gp version

openconnect-gp version:

```
OpenConnect version v7.08-1ubuntu5
Using GnuTLS. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS
```

operating system

```
Linux hostname 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

# GlobalProtect VPN information

```
POST https://vpn.example.com/ssl-vpn/login.esp
Attempting to connect to server 1.2.3.4:443
Connected to 1.2.3.4:443
SSL negotiation with vpn.example.com
Connected to HTTPS on vpn.example.com
> POST /ssl-vpn/login.esp HTTP/1.1
> Host: vpn.example.com
> User-Agent: PAN GlobalProtect
> X-Pad: 000000000000000000000000000000
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 162
> 
> jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:&server=vpn.example.com&computer=myhost&user=my.user&passwd=mypassword
Got HTTP response: HTTP/1.1 200 OK
Server: 
Date: Thu, 14 Dec 2017 17:58:18 GMT
Content-Type: application/xml; charset=UTF-8
Content-Length: 604
Connection: keep-alive
ETag: "45390-1e6f-5997180c"
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-FRAME-OPTIONS: DENY
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
Set-Cookie: PHPSESSID=XXX; secure; HttpOnly
HTTP body length:  (604)
< <?xml version="1.0" encoding="utf-8"?><jnlp><application-desc><argument>(null)</argument><argument>XXX</argument><argument>XXX</argument><argument>Company VPN-N</argument><argument>my.user</argument><argument>DUO</argument><argument>vsys1</argument><argument>example</argument><argument>(null)</argument><argument></argument><argument></argument><argument></argument><argument>tunnel</argument><argument>-1</argument><argument>4100</argument><argument></argument><argument></argument><argument></argument></application-desc></jnlp>
GlobalProtect login returned authentication source=DUO
POST https://vpn.example.com/ssl-vpn/getconfig.esp
> POST /ssl-vpn/getconfig.esp HTTP/1.1
> Host: vpn.example.com
> User-Agent: PAN GlobalProtect
> Cookie: PHPSESSID=XXX
> X-Pad: 00000000
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 248
> 
> client-type=1&protocol-version=p1&app-version=3.0.1-10&os-version=linux-64&clientos=linux-64&hmac-algo=sha1%2cmd5&enc-algo=aes-128-cbc%2caes-256-cbc&authcookie=XXX&portal=Company+VPN-N&user=my.user&domain=example
Got HTTP response: HTTP/1.1 200 OK
Server: 
Date: Thu, 14 Dec 2017 17:58:18 GMT
Content-Type: application/xml; charset=UTF-8
Content-Length: 1548
Connection: keep-alive
ETag: "4538a-1f2-5997180c"
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-FRAME-OPTIONS: DENY
HTTP body length:  (1548)
< 
< 	<response status="success">
< 		<need-tunnel>yes</need-tunnel>
< 		<ssl-tunnel-url>/ssl-tunnel-connect.sslvpn</ssl-tunnel-url>
< 		<portal>Company VPN-N</portal>
< 		<user>my.user</user>
< 		<lifetime>2592000</lifetime>
< 		<timeout>10800</timeout>
< 		<disconnect-on-idle>10800</disconnect-on-idle>
< 		<bw-c2s>1000</bw-c2s>
< 		<bw-s2c>1000</bw-s2c>
< 		<gw-address>10.37.41.20</gw-address>
< 		<ip-address>10.37.1.147</ip-address>
< 		<netmask>255.255.255.255</netmask>
< 		<dns>
< 			<member>10.32.5.218</member>
< 			<member>10.32.4.78</member>
< 		</dns> 
< 		<wins>
< 		</wins> 
< 		<default-gateway>10.37.1.147</default-gateway>
< 		<mtu>0</mtu>
< 		<dns-suffix>
< 			<member>amz.example.com</member>
< 		</dns-suffix> 
< 		<no-direct-access-to-local-network>no</no-direct-access-to-local-network>
< 		<access-routes>
< 			<member>0.0.0.0/0</member>
< 			<member>10.32.5.218/32</member>
< 			<member>10.32.4.78/32</member>
< 		</access-routes> 
< 		<ipsec>
< 			<udp-port>4501</udp-port>
< 			<ipsec-mode>esp-tunnel</ipsec-mode>
< 			<enc-algo>aes-128-cbc</enc-algo>
< 			<hmac-algo>sha1</hmac-algo>
< 			<c2s-spi>0x20DC6A9B</c2s-spi>
< 			<s2c-spi>0x83BC5F07</s2c-spi>
< 			<akey-s2c>
< 				<bits>160</bits>
< 				<val>XXX</val>
< 			</akey-s2c> 
< 			<ekey-s2c>
< 				<bits>128</bits>
< 				<val>XXX</val>
< 			</ekey-s2c> 
< 			<akey-c2s>
< 				<bits>160</bits>
< 				<val>XXX</val>
< 			</akey-c2s> 
< 			<ekey-c2s>
< 				<bits>128</bits>
< 				<val>XXX</val>
< 			</ekey-c2s> 
< 		</ipsec> 
< 	</response>
TCP_INFO rcv mss 1380, snd mss 1380, adv mss 1460, pmtu 1500
Parameters for incoming ESP: SPI 0x83bc5f07
ESP encryption type AES-128-CBC (RFC3602) key 0xXXX
ESP authentication type HMAC-SHA-1-96 (RFC2404) key 0xXXX
Parameters for outgoing ESP: SPI 0x20dc6a9b
ESP encryption type AES-128-CBC (RFC3602) key 0xXXX
ESP authentication type HMAC-SHA-1-96 (RFC2404) key 0xXXX
Send ESP probes
Connected as 10.37.1.147, using SSL
Continuing in background; pid 64199
No work to do; sleeping for 5000 ms...
No work to do; sleeping for 5000 ms...
No work to do; sleeping for 5000 ms...
No work to do; sleeping for 5000 ms...
No work to do; sleeping for 5000 ms...
Connecting to HTTPS tunnel endpoint ...
> GET /ssl-tunnel-connect.sslvpn?authcookie=XXX&portal=Company+VPN-N&user=my.user&domain=example HTTP/1.1
> 
Sending data packet of 87 bytes
Sending data packet of 87 bytes
Sending data packet of 199 bytes
Sending data packet of 199 bytes
Sending data packet of 199 bytes
Sending data packet of 68 bytes
Sending data packet of 68 bytes
Sending data packet of 199 bytes
Sending data packet of 40 bytes
No work to do; sleeping for 10000 ms...
Sending data packet of 40 bytes
No work to do; sleeping for 10000 ms...
Received data packet of 119 bytes
No work to do; sleeping for 10000 ms...
Received data packet of 119 bytes
No work to do; sleeping for 10000 ms...
```

**Comment by dlenski** [comment]
You're using openconnect-gp *and* [`vpn-slice`](//github.com/dlenski/vpn-slice)? I like you :+1: :heart_eyes:

Minor detail… you should include the `--passwd-on-stdin` option in this command line, because otherwise your password may get interpreted as the response to a different prompt from openconnect:

```sh
cat "$HOME/.secrets/vpn.passwd" |
    sudo openconnect --protocol=gp vpn.example.com --user="my.user" --background \
         --pid-file=/var/run/vpn.pid --script "vpn-slice ${SUBNETS[*]} ${HOSTS[*]}" \
         2>&1 > /var/log/vpn.log
```

All that said, I think this is pretty normal behavior and not something that openconnect can really fix. The XML `getconfig` reponse says that it's configured to kick you off the network after 3 hours :frowning_face:

```xml
 		<timeout>10800</timeout>
 		<disconnect-on-idle>10800</disconnect-on-idle>
```

Does the Windows client *not* kick you off after 3 hours?

**Comment by dlenski** [comment]
By the way, I thought about making openconnect read the `<timeout>` value not try to reconnect if it gets booted after this point… but I have seen VPNs where the value sent by the server doesn't actually match its behavior…

GlobalProtect is stupid.

**Comment by senecaso-sf** [comment]
Yep, using openconnect-gp and vpn-slice!  I'm in VPN hell over here (2 VPNs required, so you constantly need to juggle between them), so the combination of these 2 things has made my life so much easier.  I just wish I didnt have to reconnect every 3hrs.  The GP client for Mac doesnt appear to get disconnected every 3hrs, so I thought there was possibly something that openconnect-gp could be doing to handle the reconnect as well.

I agree that GP is pretty stupid.  This has been my most painful VPN experience to date.

**Comment by dlenski** [comment]
I hear you on VPN hell.

> The GP client for Mac doesnt appear to get disconnected every 3hrs, so I thought there was possibly something that openconnect-gp could be doing to handle the reconnect as well.

Hmmm… unfortunately I have no idea what this mechanism could be. If it were just a question of *idle* timeouts, then I'd have some ideas about kludges to keep the connection alive.

If it's really just a hard cutoff from the server then I don't know of any mechanism by which the official client can request an extension. Which doesn't mean that it doesn't exist… just not something that I've looked into or know about.

**Comment by dlenski** [comment]
Actually, I have an idea here…

```xml
	<lifetime>2592000</lifetime>
	<timeout>10800</timeout>
	<disconnect-on-idle>10800</disconnect-on-idle>
```

It might be that if the timeout is `n` seconds (but the lifetime is `>n`) then the client can "rekey" shortly before the timeout period runs out. This would effectively mean disconnecting, re-calling `getconfig.esp`, and thereby updating the ESP keys.

OpenConnect already has a rekey mechanism built-in, which you can see in the Cisco ('cstp.c`) and Juniper (`oncp.c`) protocol support code.

Should be possible to make this work for GP too…

**Comment by senecaso-sf** [comment]
I just talked to some others who are using the Mac client all the time, and they never need to reconnect.  The only time they actually get disconnected is if the connection is completely idle for some extended period of time (ie: the laptop is closed).  Otherwise, it is somehow renewing the tokens before expiry.  I think we can confirm this is happening because this VPN is configured to require 2FA on authentication, and that doesnt happen throughout the day, so even if the official client was caching the password, it wouldnt have a valid 2FA value, so it couldnt re-authenticate.

I have no idea what the mechanism to renew those tokens would be, but I'm pretty sure it exists :)

**Comment by senecaso-sf** [comment]
Do you now if there is a way to get debug logs from the official client?  Maybe I could enable the debug logging and leave it running for a few hours until the token renewal happens.  Might get lucky and trap some HTTPS traffic showing the endpoint required?

**Comment by dlenski** [comment]
> I have no idea what the mechanism to renew those tokens would be, but I'm pretty sure it exists :)

Yep, agreed. See my idea about re-pulling the `getconfig.esp` and integrating that with openconnect's rekey mechanism.

You should be able to easily test whether this solves the problem: replay the `POST /ssl-vpn/getconfig.esp` query 5 minutes before the expected timeout. Then replay the `POST /ssl-vpn/getconfig.esp` query again 5 minutes _after_ the expected original timeout. If the second replay _doesn't_ give you an `Invalid authentication cookie` error, then you know that the first one worked to extend the timeout. :+1:

> Do you now if there is a way to get debug logs from the official client? Maybe I could enable the debug logging and leave it running for a few hours until the token renewal happens.

Dial the PanGPS service log up to 11. It generates a ludicrous amount of data in terrible and inconsistent formats and plunks it in `C:\Program Files\Palo Alto Networks\GlobalProtect\PanGPS.log`.

![screenshot from 2017-12-13 15-54-01](https://user-images.githubusercontent.com/128716/34019632-c367709c-e0e4-11e7-95d1-0b4fb768e3e3.png)


> Might get lucky and trap some HTTPS traffic showing the endpoint required?

For that you'd need [mitmproxy](https://github.com/mitmproxy/mitmproxy), ideally including https://github.com/mitmproxy/mitmproxy/pull/2018.

After setting up mitmproxy, you'd configure your Windows/MacOS box to route all of its HTTPS traffic through the mitmproxy and watch it flow. Due to several bugs in the official GlobalProtect clients' handling of HTTP proxies, you'd need to either run mitmproxy as a *transparent* proxy (= set it up as a router) or you would need a couple traffic-mangling scripts that I've written to kinda-sorta make the HTTP proxy work.

**Comment by senecaso-sf** [comment]
ok, thanks.  I'll see if I can spend some time and try your idea of replaying the `getconfig.esp` around the time of expiry and see what happens.  Or maybe I'll just run it in a loop and capture the output and see if the keys change at some point.

**Comment by dlenski** [comment]
>Actually, I have an idea here…
>
>	<lifetime>2592000</lifetime>
>	<timeout>10800</timeout>
>	<disconnect-on-idle>10800</disconnect-on-idle>
>It might be that if the timeout is n seconds (but the lifetime is >n) then the client can "rekey" shortly before the timeout period runs out. This would effectively mean disconnecting, re-calling getconfig.esp, and thereby updating the ESP keys.
>
>OpenConnect already has a rekey mechanism built-in, which you can see in the Cisco (cstp.c) and Juniper (oncp.c) protocol support code.
>
>Should be possible to make this work for GP too… but I can make no promises about if/when I'll have time to work on it.

Assuming that I've understood how this works correctly… adding the rekeying fix to the GP protocol implementation turned out to be really easy: 7274c12dcf3fe3fd770b8343c9a64e36af8e8c22

(Kudos to @dwmw2 for designing OpenConnect's protocol-independent logic in such a thoughtful way to make this so straightforward to implement. :+1:)

**Comment by senecaso-sf** [comment]
I have built latest and I'm running it now.  We'll see if I'm still connected after 3+ hrs.

**Comment by senecaso-sf** [comment]
Somewhere around the 3hr mark I received the following messages: 
```
Error: Server asked us to submit HIP report with md5sum 70613808f65e6e5101e3e0d8bc658968.
You need to provide a --csd-wrapper argument with the HIP report submission script.
WARNING: CISCO_SPLIT_* environment variables set, but this version of vpn-slice does not handle them
```

However, the connection is still alive and appears to be working!  It has been 4hrs at this point.

**Comment by dlenski** [comment]
> Somewhere around the 3hr mark I received the following messages:
>
> ```
> Error: Server asked us to submit HIP report with md5sum 70613808f65e6e5101e3e0d8bc658968.
>

Yep, this is normal. You should see this same message at the beginning of the connection too.

After the `getconfig` request (or re-request, in this case), recent versions of openconnect-gp check if the server requires us to submit a HIP report (security scan results). Many GlobalProtect VPNs _tell_ the client that they require a HIP report (security scan) to be submitted, but they don't actually restrict or disable your access to the network if the you don't submit the HIP report.

There's no good way to distinguish (HIP report actually needed for connectivity) from (server wants HIP report but doesn't enforce it), so currently I just show the message and don't fail out.

You can take a look at [`hipreport.sh`](/dlenski/openconnect/blob/HEAD/hipreport.sh) and adapt it to spoof the format of your VPN's HIP report if needed.

> However, the connection is still alive and appears to be working! It has been 4hrs at this point.

Looks like we can close the book on this one. :+1:

**Comment by senecaso-sf** [comment]
Thanks so much for making this change!  It would have taken me forever to figure that out and make the required code changes.

**Comment by senecaso-sf** [comment]
Unfortunately, at some point later things broke.  No error message was reported, and the `openconnect` process didnt die like it used to, but I wasnt able to reach protected resources anymore.  I had to kill the `openconnect` process and restart.  I'll just have to live restarting every 3hrs.  Thanks anyway!

**Comment by dlenski** [comment]
> Thanks so much for making this change! It would have taken me forever to figure that out and make the required code changes.

Thank you for the detailed issue report and thoughtful comments. Helps a lot to make progress on this.

> … but I wasnt able to reach protected resources anymore

I'm pretty sure this is because of the lack of HIP report submission, and that if you submit a HIP report in the format used by your VPN, you'll be able to stay connected.

Try the [`hipreport.sh`](/dlenski/openconnect/blob/HEAD/hipreport.sh) template as-is, or see [this comment on #70](https://github.com/dlenski/openconnect/pull/70#issuecomment-349345068) for a couple ideas about how to extract the HIP report sent by an official client.
