### ISSUE TITLE
Merge Upstream?

### ISSUE THREAD

**Issue by dannyman** [dlenski/openconnect#74]
Please forgive me, but I love this fork of OpenConnect and I would like to see it more widely available. Is there any chance of committing changes upstream to the parent project?

http://www.infradead.org/openconnect/contribute.html

By my reading, anyone could submit the patches published here, due to GPL, but it is @dlenski who did the work, ought to get the credit, and is probably best equipped to pull up a patch.

This could be very convenient for folks if it just ends up in their OS package manager.

Thank You,
-danny

**Comment by dlenski** [comment]
Yes, getting it merged upstream has been my goal since day 1.

You can see some progress and a list of todo items for me on the [mailing list](http://www.infradead.org/openconnect/mail.html).

**Comment by dannyman** [comment]
<3
