### ISSUE TITLE
2-Factor Authentication

### ISSUE THREAD

**Issue by ryanwoconnor** [dlenski/openconnect#83]
Does this version support 2-Factor Authentication? Or can we make it do that some time? My auth fails but I'm 90% sure that's because I don't get prompted for a second factor of auth.

**Comment by dlenski** [comment]
> does this version …

You didn't say *which* version you're running. I've supported all the GP 2FA cases I know about for almost a year.

See #67, #57?

**Comment by KriCG** [comment]
@dlenski What is the command for openconnect to connect with two factor authentication ?

**Comment by dlenski** [comment]
* are you using the official upstream OpenConnect 8.x, as specified on the front page of this repo?
* did you read the manual of openconnect's command-line options? https://www.infradead.org/openconnect/manual.html
* you already saw the comments on #67 and #83… did you try what I suggested there?

**Comment by KriCG** [comment]
I download version 8 and installed on linux server.


[root@target10 kvittal]# openconnect url --user=user --protocol=anyconnect --token-mode=rsa
OpenConnect was not built with libstoken support

**Comment by KriCG** [comment]
and the libstoken is a ubuntu package ...

**Comment by dlenski** [comment]
> I download version 8 and installed on linux server.
> ```
> [root@target10 kvittal]# openconnect url --user=user --protocol=anyconnect --token-mode=rsa
> OpenConnect was not built with libstoken support
> ```

What is ‘version 8’? Exactly where did you download from?

I'm assuming this means you built it from _source_… if that's correct, did you install the `libstoken-dev` package, then run `./configure` ­and verify that it shows stoken support?

```
BUILD OPTIONS:
  SSL library:            GnuTLS
  PKCS#11 support:        GnuTLS
  DTLS support:           yes
  ESP support:            yes
  libproxy support:       yes
  RSA SecurID support:    yes # will say 'no' if it doesn't detect stoken library and headers
  PSKC OATH file support: no
  GSSAPI support:         yes
  Yubikey support:        yes
  LZ4 compression:        yes
  Java bindings:          no
  Build docs:             yes
  Unit tests:             yes
  Net namespace tests:    no
```

**Comment by KriCG** [comment]
yum -y install libstoken-dev
Loaded plugins: amazon-id, product-id, replace, rhui-lb, search-disabled-repos, security, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Repository nodesource is listed more than once in the configuration
Repository nodesource-source is listed more than once in the configuration
Setting up Install Process
No package libstoken-dev available.
Error: Nothing to do

**Comment by KriCG** [comment]
`# yum -y install libstoken-dev
Loaded plugins: amazon-id, product-id, replace, rhui-lb, search-disabled-repos, security, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Repository nodesource is listed more than once in the configuration
Repository nodesource-source is listed more than once in the configuration
Setting up Install Process
No package libstoken-dev available.
Error: Nothing to do`

There is no package available !! Should I download libstoken as well ?

**Comment by dlenski** [comment]
> There is no package available !! Should I download libstoken as well ?

:man_facepalming: 

Above you said you were using **Ubuntu**. Now you show that you're using a `yum`-based distro (CentOS, RHEL?).

Figure out the correct name of the stoken development package for _your distro_, and install that.
