### ISSUE TITLE
Ubuntu PPA no longer works

### ISSUE THREAD

**Issue by willguxy** [dlenski/openconnect#84]
Hi. Pretty sure it's not the best place to ask this question. But it seems that `http://ppa.launchpad.net/lenski/openconnect-gp/ubuntu` is not working any more

**Comment by dlenski** [comment]
Right. I deleted it. I haven't been able to update it for almost a _year_, because the versioning and structure which you have to follow for a PPA is quite tricky. (I'm not saying there are no good reasons for it … it's just hard for me to fit into the development process here).

Now I'm getting a large number of issue reports and emails about problems with the software which have been fixed since I made the PPA. So I thought it'd better go.

**Comment by AlexandreSNeto** [comment]
@dlenski I do not know the process to add an application into a PPA, but there is no way to automate a build process (with travis, for example) to add the application into the PPA, so you no longer need to worry in keep it up to date ?

**Comment by dlenski** [comment]
@AlexandreSNeto, there is indeed. Patches to build the DEBs automatically, while updating the version information and changelog correctly, would be most welcome :-D

**Comment by dlenski** [comment]
It appears that @gbonnefille has built a fork where he is building .deb packages :+1: 

https://github.com/gbonnefille/openconnect/

**Comment by gbonnefille** [comment]
I did a try, but without any intention to publish the deb. Note that this work is done by @loplex [here](https://github.com/loplex/openconnect).

On a related topic: is there any intention to merge back this work on the official openconnect project?

**Comment by dlenski** [comment]
> I did a try, but without any intention to publish the deb. Note that this work is done by @loplex here.

Good to know… thanks!

> On a related topic: is there any intention to merge back this work on the official openconnect project?

Yep, you can find lots of discussion in the [official openconnect mailing list archives](http://lists.infradead.org/pipermail/openconnect-devel/).

**Comment by gbonnefille** [comment]
> Yep, you can find lots of discussion in the official openconnect mailing list archives.

I found some messages about a possible integration after the 7.08 release. But nothing more clear (for me). What is the effective status of this topic? How can I help to have your patches merged back?

**Comment by dlenski** [comment]
> I found some messages about a possible integration after the 7.08 release. But nothing more clear (for me). What is the effective status of this topic? How can I help to have your patches merged back?

Not sure. Openconnect's [BDFL](https://en.wikipedia.org/wiki/BDFL), David Woodhouse, has given me several rounds of excellent and useful feedback on my changes…

… at this point I'm not sure what else he needs besides "free time to take another look at them" :joy:
