### ISSUE TITLE
Assign private IP address failed

### ISSUE THREAD

**Issue by dufflecoat-philosopher** [dlenski/openconnect#86]
# Problem description

1. I ran openconnect-gp as follows: `openconnect --protocol=gp --os=win --useragent='PAN GlobalProtect' myco.com`
2. I have been successfully using this to our old portal for the last 8 months (for which many thanks) but trying it on the new one fails with Assign private IP address failed. It gets past the authentication OK. The windows client connects OK with same login details, same local network. Our hosts just say "we dont support Linux"
3.
4.

# Operating system and openconnect-gp version

openconnect-gp version: 

OpenConnect version v7.08-229-ge4ef149
Using GnuTLS. Features present: PKCS#11, HOTP software token, TOTP software token, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp

# Operating system:

Linux Linux 4.8.17-tinycore64 #2017 SMP Sun Mar 5 17:17:31 UTC 2017 x86_64 GNU/Linux

# GlobalProtect VPN information

```
Please enter your username and password
Username: me
Password: 
POST https://myco.com/ssl-vpn/login.esp
Attempting to connect to server my.co.IP.addr:443
Connected to my.co.IP.addr:443
SSL negotiation with myco.com
Connected to HTTPS on myco.com
> POST /ssl-vpn/login.esp HTTP/1.1
> Host: myco.com
> User-Agent: PAN GlobalProtect
> X-Pad: 0000000000000000000000000000000000000000000000000000
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 140
> 
> jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:&server=myco.com&computer=me&user=me&passwd=pwd
Got HTTP response: HTTP/1.1 200 OK
Server: 
Date: Thu, 01 Feb 2018 18:48:08 GMT
Content-Type: application/xml; charset=UTF-8
Content-Length: 607
Connection: keep-alive
ETag: "13ece-1e54-590bf207"
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-FRAME-OPTIONS: DENY
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
Set-Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b; secure; HttpOnly
HTTP body length:  (607)
< <?xml version="1.0" encoding="utf-8"?><jnlp><application-desc><argument>(null)</argument><argument>afb94e0eb6c685b0ef2aea7da31d1405</argument><argument>5280c38e07546150890714e5baa33c9bc32eec3c</argument><argument>globalprotect-N</argument><argument>me</argument><argument>globalprotect</argument><argument>vsys1</argument><argument>mydomain</argument><argument>(null)</argument><argument></argument><argument></argument><argument></argument><argument>tunnel</argument><argument>-1</argument><argument>4100</argument><argument></argument><argument></argument><argument></argument></application-desc></jnlp>
GlobalProtect login returned authentication-source=globalprotect
POST https://myco.com/ssl-vpn/getconfig.esp
> POST /ssl-vpn/getconfig.esp HTTP/1.1
> Host: myco.com
> User-Agent: PAN GlobalProtect
> Cookie: PHPSESSID=171be3cb2ad90c9d875acb320d09915b
> X-Pad: 0000000000000000000000000
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 231
> 
> client-type=1&protocol-version=p1&app-version=3.0.1-10&os-version=win&clientos=win&hmac-algo=sha1%2cmd5&enc-algo=aes-128-cbc%2caes-256-cbc&authcookie=afb94e0eb6c685b0ef2aea7da31d1405&portal=globalprotect-N&user=my&domain=mydomain
Got HTTP response: HTTP/1.1 200 OK
Server: 
Date: Thu, 01 Feb 2018 18:48:09 GMT
Content-Type: application/xml; charset=UTF-8
Content-Length: 147
Connection: keep-alive
ETag: "13ec8-1f2-590bf207"
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-FRAME-OPTIONS: DENY
HTTP body length:  (147)
< 
<       <response status="error">
<               <portal>globalprotect-N</portal>
<               <user>me</user>
<               <error>Assign private IP address failed</error>
<       </response>
Assign private IP address failed
Creating SSL connection failed
```

**Comment by dlenski** [comment]
Interesting. I have a theory about why this could happen, but not 100% sure.

When you connect from a Windows client, do you get the same VPN-internal IP address every time … or does it change every time you connect?

**Comment by dufflecoat-philosopher** [comment]
Tried the windows client, reconnected several times over the last few  
days and it was the same assigned IP every time.

**Comment by dlenski** [comment]
Yep, that's what I suspected.

In 24bc277ebdbd438aa3020a06374f0cdb7cb1327e I added an option (`--request-ip A.B.C.D`) to request a specific IP address from the server… because some GP VPNs don't seem to work _at all_ without having the right IP address requested specifically. :-1: 

If you use this option with the same address given by the Windows client… does it work?

**Comment by dufflecoat-philosopher** [comment]
No, no change. Now using OpenConnect version v7.08-265-gae48121.
I wondered about HIP checks - https://www.paloaltonetworks.com/documentation/71/pan-os/web-interface-help/globalprotect/objects-globalprotect-hip-objects . I think this is enabled , there is certainly HIP.log etc on the windows box.

**Comment by dlenski** [comment]
> I wondered about HIP checks

Have you read [the HIP docs](//github.com/dlenski/openconnect/blob/HEAD/www/hip.xml) and attempted to use the `--csd-wrapper hipreport.sh` to generate a spoofed report?

**Comment by dufflecoat-philosopher** [comment]
I have now. Hadn't realised the connection between HIP and CSD. However, nothing I do seems to run that script. Tried adding echo msgs in that script to a CSD.log, it doesnt get run. I have even copied the xml from the windows log to a file and made my own .sh that simply cats it. No difference, it doesn't get run. I have tried 2 stage login with authenticate first to get the cookie, no joy. Same for all-in-one, all params on one line. I can see from the windows PANgps.log that the server response is hip_report_needed = no but the client does send one. Even tried reading the code (its a lot of years since I did any C) and your comments in gpst.c imply that it should require the 2 stage approach or maybe it handles those 2 stages internally. Not sure what else to try now.

**Comment by dlenski** [comment]
Did you set the permissions on the HIP script to ensure that it's executable?

**Comment by dufflecoat-philosopher** [comment]
I have been running with -vvvv and --dump-http-traffic but these is no mention of HIP at all in the output. It is useful to know that I dont need to manually run 2 stages so thanks for clearing that up. 
I've now compared the debug trail between the 2 PANGP servers I have access to and the failing one fails before the HIP stage, I can see the working one doing the "running HIP anyway" patch later on. So HIP is red herring. Apologies, my fault but until all this I didn't even know what HIP was.
So we are back where we started.

**Comment by dlenski** [comment]
> I've now compared the debug trail between the 2 PANGP servers I have access to and the failing one fails before the HIP stage, I can see the working one doing the "running HIP anyway" patch later on.

Yeah, upon re-reading your log, it's clear that the HIP report won't help because the error is happening on the `getconfig` request, which is *before* the HIP report gets checked/submitted.

> So we are back where we started.

Right.

There is _something_ that the Windows client does differently from what openconnect does with this server, which makes the server respond differently. And we don't know what it is.

My initial educated guess was that it had to do with using a pre-assigned IP address, but **you said you checked this and it made no difference**… right?

Now I don't have any ideas. In order to make progress, you would need to use `mitmproxy` to log the traffic between the Windows client and the GP server, in order to figure out what's different. [I gave some advice about how to do it here, on issue #78](https://github.com/dlenski/openconnect/issues/78#issuecomment-356794345).

**Comment by dufflecoat-philosopher** [comment]
Yes, I am using request-ip=X. Spent some time with mitm. Neat, shame about the dump to file format. I only include the first 2 steps because thats where it fails. Also, there appeared to be 2 certificates on every request. The 2nd is labelled mitmcert so presume that is Windows talking to Proxy but no idea where the 1st comes from. There is also mention of TLS in amongst those bits. Again, thats mitm, the GUI is great, getting output is awful. Oh well, I found a few things and the trails are very different.

**1st POST**
OCGP - https://myco.com/ssl-vpn/login.esp?jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:&server=myco.com&computer=me&user=me&passwd=pwd

WinGP - https://myco.com/global-protect/prelogin.esp?kerberos-support=yes&tmp=tmp&clientVer=4100&host-id=MyUUID&clientos=Windows&os-version=Microsoft+Windows+10+Home+%2c+64-bit&ipv6-support=yes

NOTE - prelogin.esp???
NOTE - no User/Password from WinGP client at this stage
NOTE - WinGP seemed to repeat this but I could see no fail response in between

**2nd POST**
OCGP - https://myco.com/ssl-vpn/getconfig.esp?client-type=1&protocol-version=p1&app-version=3.0.1-10&os-version=win&clientos=win&hmac-algo=sha1%2cmd5&enc-algo=aes-128-cbc%2caes-256-cbc&authcookie=CookieID&portal=globalprotect-N&user=my&domain=mydomain
FAILS with Assign private IP address failed

NOTE - Why is app-version different to clientVer in 1st POST? Maybe they are different things.

WinGP - https://myco.com/global-protect/getconfig.esp?user=MyLogin&passwd=MyPassword&inputStr=&ok=Login&clientVer=4100&portal-userauthcookie=empty&portal-prelogonuserauthcookie=empty&clientos=Windows&clientgpversion=4.0.2-19&computer=HP_LAPTOP1&os-version=Microsoft+Windows+10+Home+%2c+64-bit&host-id=MyUUID&prelogin-cookie=&ipv6-support=yes

NOTE - passes login/password at this stage

Response (sorry theres quite a bit of this):
`<?xml version="1.0" encoding="UTF-8" ?>
<policy>
	<portal-name>eu.globalprotect</portal-name>
	<portal-config-version>4100</portal-config-version>
	<version>4.0.2-19                                                        </version>
	<client-role>global-protect-full</client-role>
	<agent-user-override-key>****</agent-user-override-key>
	<root-ca>
		<entry name="xxxx.root.ca">
			<cert>
-----BEGIN CERTIFICATE-----
Cert received from GPS, this is the same every time. We do not appear to send it back
-----END CERTIFICATE-----
			</cert>
			<install-in-cert-store>no</install-in-cert-store>
		</entry>
	</root-ca>
	<connect-method>on-demand</connect-method>
	<on-demand>yes</on-demand>
	<refresh-config>yes</refresh-config>
	<refresh-config-interval>24</refresh-config-interval>
	<authentication-modifier>
		<none/>
	</authentication-modifier>
	<authentication-override>
		<accept-cookie>no</accept-cookie>
		<generate-cookie>no</generate-cookie>
		<cookie-encrypt-decrypt-cert></cookie-encrypt-decrypt-cert>
	</authentication-override>
	<use-sso>no</use-sso>
	<internal-host-detection>
		<ip-address>10.x.y.z</ip-address>
		<host>neverheardofthis.myco.com</host>
	</internal-host-detection>
	<gateways>
		<cutoff-time>5</cutoff-time>
		<external>
			<list>
				<entry name="vpn.myco.com">
					<priority>1</priority>
					<description>globalprotect</description>
				</entry>
			</list>
		</external>
	</gateways>
	<agent-ui>
		<can-save-password>no</can-save-password>
		<passcode></passcode>
		<agent-user-override-timeout>0</agent-user-override-timeout>
		<max-agent-user-overrides>0</max-agent-user-overrides>
		<help-page></help-page>
		<welcome-page>
			<display>no</display>
			<page></page>
		</welcome-page>
<agent-user-override>disabled</agent-user-override>
<enable-advanced-view>yes</enable-advanced-view>
<enable-do-not-display-this-welcome-page-again>yes</enable-do-not-display-this-welcome-page-again>
<can-change-portal>yes</can-change-portal>
<show-agent-icon>yes</show-agent-icon>
<password-expiry-message></password-expiry-message>

	</agent-ui>
	<hip-collection>
		<hip-report-interval>3600</hip-report-interval>
		<max-wait-time>20</max-wait-time>
		<collect-hip-data>yes</collect-hip-data>
		<default>
			<category>
				<member>host-info</member>
				<member>data-loss-prevention</member>
				<member>patch-management</member>
				<member>firewall</member>
				<member>antivirus</member>
				<member>anti-spyware</member>
				<member>disk-backup</member>
				<member>disk-encryption</member>
			</category>
		</default>
	</hip-collection>
	<agent-config>
	<save-user-credentials>0</save-user-credentials>
	<portal-2fa>no</portal-2fa>
	<internal-gateway-2fa>no</internal-gateway-2fa>
	<auto-discovery-external-gateway-2fa>no</auto-discovery-external-gateway-2fa>
	<manual-only-gateway-2fa>no</manual-only-gateway-2fa>
<client-upgrade>transparent</client-upgrade>
<logout-remove-sso>yes</logout-remove-sso>
<krb-auth-fail-fallback>yes</krb-auth-fail-fallback>
<retry-tunnel>30</retry-tunnel>
<retry-timeout>5</retry-timeout>
<enforce-globalprotect>no</enforce-globalprotect>
<captive-portal-exception-timeout>0</captive-portal-exception-timeout>
<traffic-blocking-notification-delay>15</traffic-blocking-notification-delay>
<display-traffic-blocking-notification-msg>yes</display-traffic-blocking-notification-msg>
<traffic-blocking-notification-msg>&lt;div style=&quot;font-family:'Helvetica Neue';&quot;&gt;&lt;h1 style=&quot;color:red;text-align:center; margin: 0; font-size: 30px;&quot;&gt;Notice&lt;/h1&gt;&lt;p style=&quot;margin: 0;font-size: 15px; line-height: 1.2em;&quot;&gt;To access the network, you must first connect to GlobalProtect.&lt;/p&gt;&lt;/div&gt;</traffic-blocking-notification-msg>
<allow-traffic-blocking-notification-dismissal>yes</allow-traffic-blocking-notification-dismissal>
<display-captive-portal-detection-msg>no</display-captive-portal-detection-msg>
<captive-portal-detection-msg>&lt;div style=&quot;font-family:'Helvetica Neue';&quot;&gt;&lt;h1 style=&quot;color:red;text-align:center; margin: 0; font-size: 30px;&quot;&gt;Captive Portal Detected&lt;/h1&gt;&lt;p style=&quot;margin: 0; font-size: 15px; line-height: 1.2em;&quot;&gt;GlobalProtect has temporarily permitted network access for you to connect to the Internet. Follow instructions from your internet provider.&lt;/p&gt;&lt;p style=&quot;margin: 0; font-size: 15px; line-height: 1.2em;&quot;&gt;If you let the connection time out, open GlobalProtect and click Connect to try again.&lt;/p&gt;&lt;/div&gt;</captive-portal-detection-msg>
<certificate-store-lookup>user-and-machine</certificate-store-lookup>
<scep-certificate-renewal-period>7</scep-certificate-renewal-period>
<ext-key-usage-oid-for-client-cert></ext-key-usage-oid-for-client-cert>
<retain-connection-smartcard-removal>yes</retain-connection-smartcard-removal>
<rediscover-network>no</rediscover-network>
<resubmit-host-info>no</resubmit-host-info>
<can-continue-if-portal-cert-invalid>yes</can-continue-if-portal-cert-invalid>
<user-switch-tunnel-rename-timeout>0</user-switch-tunnel-rename-timeout>
<pre-logon-tunnel-rename-timeout>-1</pre-logon-tunnel-rename-timeout>
<show-system-tray-notifications>no</show-system-tray-notifications>
<max-internal-gateway-connection-attempts>0</max-internal-gateway-connection-attempts>
<portal-timeout>30</portal-timeout>
<connect-timeout>60</connect-timeout>
<receive-timeout>30</receive-timeout>
<flush-dns>no</flush-dns>
<proxy-multiple-autodetect>no</proxy-multiple-autodetect>
<wsc-autodetect>yes</wsc-autodetect>
<ipv6-preferred>yes</ipv6-preferred>`

**Comment by dufflecoat-philosopher** [comment]
I doubt this tells you anything you dont already know but I found it interesting: http://palo-alto.wikia.com/wiki/Global_Protect

**Comment by dlenski** [comment]
Right. To put it very briefly, none of this is a surprise to me… but it's very helpful to see the portal configuration which you've included above, and confirm that there's nothing new or special in it :+1:

The Windows client starts off with a request of  `/global-protect/prelogin.esp` ("portal pre-login"), followed by a request of `/global-protect/getconfig.esp` ("portal config"). These requests are both more-or-less useless, which is why OpenConnect doesn't bother with them unless you use a server address of `vpn.myco.com/portal`, in which case it *does* perform the `/global-protect/getconfig.esp` request to fetch the portal config and get the list of available gateway servers (`<gateways><external><list>…`).

Try connecting with `openconnect vpn.myco.com/portal` and see if it makes a difference, but I doubt it.

I think the real interesting part here will come after…

What does the Window client do **after** these initial two requests, when it should request `/ssl-vpn/login.esp` and then `/ssl-vpn/getconfig.esp` (same as what openconnect requests)? How do those requests differ from what openconnect requests?

Your portal config contains `<can-continue-if-portal-cert-invalid>yes</can-continue-if-portal-cert-invalid>`, so the Windows client _should_ allow you to continue (with a warning) despite the fact that the MITM certificate doesn't match the expected server certificate (from `<root-ca>` in the portal config).

**Comment by dlenski** [comment]
> Neat, shame about the dump to file format. …  Again, thats mitm, the GUI is great, getting output is awful.

Not sure what you mean. Have you tried `mitmdump`, which will log output to a file?

You might want to take a look at [PAN_GlobalProtect_protocol_doc.md](https://github.com/dlenski/openconnect/blob/HEAD/PAN_GlobalProtect_protocol_doc.md) for the format in which I document the back-and-forth exchanges of the authentication protocol, insofar as I know it.

**Comment by dufflecoat-philosopher** [comment]
Yes, I see what you mean, sorry for being dim. Actually it does yet another prelogin next but after that it is as you suspected:

**Comment by dlenski** [comment]
The only things that _might_ be relevant in this request are the fact that the Windows client passes `addr1` and `addr-v6-1` and `addr-v6-2` to the server. (`openconnect` doesn't).

```
https://myco.com/ssl-vpn/getconfig.esp?user=MyLogin&addr1=My.Local.IP.Addr/24&addr-v6-1=2001::/32&addr-v6-2=2001:0:xxxx:xxxx:xxxx:xxxx:xxxx:xxx/128&preferred-ip=My.Pref_IP_Addr&preferred-ipv6=&portal=globalprotect-N&authcookie=CookieID&client-type=1&os-version=Microsoft%20Windows%2010%20Home%20,%2064-bit&app-version=4.0.2-19&protocol-version=p1&clientos=Windows&ipv6-support=yes&enc-algo=aes-256-gcm,aes-128-gcm,aes-128-cbc,&hmac-algo=sha1
```

Try hard-coding these [into the `ssl-vpn/getconfig.esp` request](https://github.com/dlenski/openconnect/blob/HEAD/gpst.c#L563) and see if it makes a difference…?

Otherwise, it appears that the requests issued by the Windows client do not differ in any way that could meaningfully affect IP address assignment…

**Comment by dufflecoat-philosopher** [comment]
Tried adding those to gpst.c - no change BUT ... just simulated it all in Postman (on Linux) and it works in so far as the 4th of these steps returns the above success response as per Windows GP:

1. global-protect/prelogin.esp
2. global-protect/getconfig.esp
3. ssl-vpn/login.esp
4. ssl-vpn/getconfig.esp (using 1st argument from 3) 

Still struggling to see what I am doing in Postman that oc-gp is not doing but its progress. Will try and spot the difference tomorrow.

**Comment by dlenski** [comment]
Nice work. You're clearly making good progress here.

If you omit the first two requests entirely (`/global-protect`) and only

**Comment by dlenski** [comment]
… replay the last two (`/ssl-vpn`), do you get the same successful result?

I've never seen a case before where the first two ("portal ") requests affect the success or failure of the subsequent two (" gateway ")  requests, and I have some strong reason to suspect that it'd be impossible for them to interact in this way given the architecture of GP. But I'd also be interested if I'm proven wrong.

**Comment by dufflecoat-philosopher** [comment]
Yes it only requires the last 2 stages.
I have tried stripping down both steps to the bare minimum it will work with and those are  all supplied by oc-gp (italicised where it doesnt seem to care what the contents are):
- login.esp: jnlpready, user, password, ok=Login, direct=yes
- getconfig.esp: user, portal, authcookie, client-type, _os-version_, _app-version_, protocol-version
So if ocgp is providing the minimum OK then maybe there is something additional it is providing that breaks it. The 1st extra thing I tried adding in Postman was domain and that broke it. I now get the IP assign error. Not only that but after removing domain it remains broken and I can not get it to work again. 
The reason I chose domain is because it is not my domain. ocgp assumes that the middle bit of the url is my domain, it isnt. The URL is for 3rd party hosting company. 
Now to try and get it back working again.

**Comment by dlenski** [comment]
> Yes it only requires the last 2 stages.
> I have tried stripping down both steps to the bare minimum it will work with and those are  all supplied by oc-gp (italicised where it doesnt seem to care what the contents are):
> - login.esp: jnlpready, user, password, ok=Login, direct=yes
> - getconfig.esp: user, portal, authcookie, client-type, _os-version_, _app-version_, protocol-version

You are doing the exact right thing here.

> The 1st extra thing I tried adding in Postman was domain and that broke it. I now get the IP assign error. Not only that but **after removing domain it remains broken and I can not get it to work again.**

Woahhh… that's weird, especially the "sticky" behavior.

> The reason I chose domain is because it is not my domain. ocgp assumes that the middle bit of the url is my domain, it isnt.

openconnect is *not* getting the domain from the URL. openconnect is getting the domain from the `ssl-vpn/login.esp` response:

```xml
<argument>(null)</argument>
<argument>32 Char Key</argument>
<argument>40 Char Key</argument>
<argument>globalprotect-N</argument>
<argument>MyLogin</argument>
<argument>globalprotect</argument>
<argument>vsys1</argument>
<argument>MyCo</argument><!-- This is the domain -->
<argument>(null)</argument>
<argument></argument>
<argument></argument>
<argument></argument>
<argument>tunnel</argument>
<argument>-1</argument>
<argument>4100</argument>
<argument>My.Pref.IP.Addr</argument>
<argument>empty</argument>
<argument>empty</argument>
```

See here: https://github.com/dlenski/openconnect/blob/HEAD/auth-globalprotect.c#L68-L85

> The URL is for 3rd party hosting company.

Wait… what!??! Are you controlling the PAN GP server *yourself*?

**Comment by dufflecoat-philosopher** [comment]
Sorry, I must have worded that badly. No, I have no control over the PAN GP server. What I meant was that the URL is something like vpn.hostingco.com and the domain argument passed back by the login response is that hostingco, it is not the domain of my actual company so I thought - lets try that. Had to abandon testing for now to do some paid work, will try again after a reboot later

**Comment by dlenski** [comment]
> What I meant was that the URL is something like vpn.hostingco.com and the domain argument passed back by the login response is that hostingco, it is not the domain of my actual company and is the ONLY thing passed by ocgp not passed by windows so I thought - lets try that.

Ah, got it. That's a good observation :+1:.

Huh… I don't understand how the Windows client receives that field but doesn't save it as the `domain` field.

**Comment by dufflecoat-philosopher** [comment]
Success! I now have a working version of ocgp and am connected and RDP'ing over it. Its a pretty rubbish solution. The key is the clientos param but there is a trail:
- the stickiness of errors can be fixed by posting a logout. I think you have to do the full login, getconfig, logout process before changing any params. It is not a valid test to do a login then multiple posts of getconfig
- clientos is not required in itself for login but _is_ for getconfig and that requires that it be the same value as in login therefore we _do_ have to provide it at login
- clientos MUST = Windows, not win. That is a problem because the only documented related OC param is os which only allows os=win, linux, mac-os etc
- there are other situations where a param is pointless in its own right but must match an earlier posting, eg Computer=MyLaptop must be the same in login and logout

I hardcoded clientos=Windows into the http params in auth-globalprotect.c and gpst.c and now it works. Not sure how to work that in neatly but it occurs to me that there are a lot of GP specific params not catered for by the generic OC and while most of them seem to be pointless we have no way of sending them in OC. Maybe GP-prefixed params in config? OTOH it would be a tedious amount of work to allow all of them when most are pointless.

I wont close this yet, will see if you want to amend your code and if so I'll test it.

**Comment by dlenski** [comment]
> Success! I now have a working version of ocgp and am connected and RDP'ing over it. Its a pretty rubbish solution. The key is the clientos param but there is a trail:

Very well done :+1: :+1: :+1: :+1: :+1: 

> - the stickiness of errors can be fixed by posting a logout. I think you have to do the full login, getconfig, logout process before changing any params. It is not a valid test to do a login then multiple posts of getconfig

That is extremely strange. There are other contexts in which it is essentially *necessary* to repeat `ssl-vpn/getconfig.esp` multiple times after a single `ssl-vpn/login.esp` (for example) rekeying… but I don't doubt your assessment. :man_facepalming: 

> - clientos is not required in itself for login but _is_ for getconfig and that requires that it be the same value as in login therefore we _do_ have to provide it at login

Aha! That's crucial. Good catch.

> - clientos MUST = Windows, not win. That is a problem because the only documented related OC param is os which only allows os=win, linux, mac-os etc

Got it. The official client [always says `Windows`](https://github.com/dlenski/openconnect/blob/globalprotect/PAN_GlobalProtect_protocol_doc.md#login-request) so I should make it so that openconnect does the same… it was a sloppy shortcut of me to do otherwise, because it didn't seem to matter.

> - there are other situations where a param is pointless in its own right but must match an earlier posting, eg Computer=MyLaptop must be the same in login and logout

Yes. [Don't get me started on how stupid this is](https://github.com/dlenski/openconnect/blob/globalprotect/PAN_GlobalProtect_protocol_doc.md#logout-request) to make the client parrot back a bunch of random non-secret parameters to the server… but it is true.

> 
> I hardcoded clientos=Windows into the http params in auth-globalprotect.c and gpst.c and now it works. Not sure how to work that in neatly but it occurs to me that there are a lot of GP specific params not catered for by the generic OC and while most of them seem to be pointless we have no way of sending them in OC. Maybe GP-prefixed params in config? **OTOH it would be a tedious amount of work to allow all of them when most are pointless.**

Exactly. There's a lot of stuff which GP includes which seems to be pointless/redundant/arbitrary… you've discovered one case where the value *really does matter*.

Let me make a minimal patch for this case…

**Comment by dlenski** [comment]
> Okay, hold on a sec here… you're saying two things:
> 
> 1. The `clientos` argument for `login.esp` and `getconfig.esp` must **match** (easy… I can do that)
> 2. The `clientos` argument must be **`Windows`**, not **`win`**.
> 
> Are *both* of these true, or only \#1? I suspect that it's only \#1, and that the actual value is arbitrary.

I made a patch that **only** does \#1 (submits same `client-os` and `os-version` values for both requests).

Please test 73f46be and tell me if it works.

**Comment by dufflecoat-philosopher** [comment]
Will do but can't right now. Pretty sure from Postman that the value does matter but agree its worth being sure.

**Comment by dlenski** [comment]
Thanks a lot. I will set the value to "Windows" if necessary, but I'm just trying to verify that I'm not adding extra arbitrary stuff which _isn't_ necessary.

**Comment by dufflecoat-philosopher** [comment]
Tested and I'm afraid it fails with the original error. I don't think os-version is relevant just clientos but that does need to be "Windows". Why? Who knows. At least they haven't enabled any of the nastier HIP stuff. 
Thanks for your help in this, I've quite enjoyed learning about mitmproxy and postman and now I dont have to resort to using Windows

**Comment by dlenski** [comment]
Thanks for the follow-up. You've gotten really good at this really fast. 👍

I'll add a patch to translate it to `Windows` in both requests in a sec.

**Comment by dufflecoat-philosopher** [comment]
Yep, recloned and built from scratch and it all works fine now, thanks.
A nice-to-have would be the ability to set all those pointless params so that to anyone studying the server logs this is indistinguishable from the Windows client. But thats probably paranoia and I can always hardcode them, thats the beauty of opensource.
Closing this issue.
