### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by andrewrk** [dlenski/openconnect#88]
it's been over a year since the last one and there has been lots of work done

**Comment by dlenski** [comment]
I haven't/won't create official releases. Those are managed upstream.

The intention of this repo is to get it merged into the "official" openconnect … and then to disappear :-D

**Comment by andrewrk** [comment]
Aha, excellent. Well, here's the update to network manager: https://github.com/andrewrk/network-manager-openconnect/compare/add-globalprotect

I'm running your code + this at work to access the VPN and it's working great.

What's the next step toward getting this merged upstream?

**Comment by dlenski** [comment]
> Well, here's the update to network manager:

Did you see https://github.com/dlenski/network-manager-openconnect ?

You can find some conversations between David Woodhouse (openconnect author /BDFL) and me on the official mailing list … along with numerous patches I've submitted.

At this point it's probably a matter of David Woodhouse having enough time and bandwidth to take a look at all of my patches and giving me more specific feedback on what needs to be addressed before it can be merged. I believe I addressed most of his earlier issues with sloppy memory handling in the GP code.

**Comment by dlenski** [comment]
Looks like your NM plugin changes add GP by hard coding it into the list of supported plugins.

What I did, and which has already been merged upstream (both in openconnect *and* in the NM plugin) was to add an API to libopenconnect to allow the front-end to find out the supported protocols and some of their properties.
