### ISSUE TITLE
Selective routing

### ISSUE THREAD

**Issue by vonkad** [dlenski/openconnect#91]
I'm sorry I do not fit into the categories described in the template. I just have a question/need help with use.

I would like to route just a part of network traffic through the VPN. Just a specific URL or a specific IP address. Is it possible ?

**Comment by dlenski** [comment]
Check out [dlenski/vpn-slice](/dlenski/vpn-slice) which I wrote for exactly this purpose, and which integrates nicely with `openconnect`.
