### ISSUE TITLE
Merge into official openconnect

### ISSUE THREAD

**Issue by candrews** [dlenski/openconnect#94]
Can you please submit these changes to the official openconnect project so that everyone (linux distros and the like) can enjoy this work?

Thanks!

**Comment by MetricMike** [comment]
Hi @candrews - this is a work-in-progress at the [official openconnect mailing list archives](http://lists.infradead.org/pipermail/openconnect-devel/). They're down at the moment, but dlenski's comment [here](https://github.com/dlenski/openconnect/issues/84#issuecomment-367691208) implies that we're just waiting for free time on the openconnect's BDFL part for review.

**Comment by dlenski** [comment]
> … dlenski's comment here implies that we're just waiting for free time on the openconnect's BDFL part for review.

Thanks @MetricMike. Honestly, there will probably be some additional cleanup required by me.

But I'm already devoting as much time and effort to getting this merged as I can.

**Comment by candrews** [comment]
Can we please reopen this issue and keep it open until the merge is done, so that it's easy for those of us who are interested to learn about the progress and find it when it's complete?

**Comment by dlenski** [comment]
@candrews, I could but… "getting this merged into upstream" is too non-specific — and outside the scope of the repository itself — to be an actionable issue.

Including some information on the progress of merging upstream in the README would probably be a better way to keep users informed.

What do you think of doing that instead?

**Comment by candrews** [comment]
The ticket it nice because people can subscribe to it and get notified on updates, as opposed to the README that will have to checked periodically :)

**Comment by dlenski** [comment]
If you want detailed development updates… follow the `openconnect-devel` mailing list.

From the user perspective, the only meaningful update ever is going to be "Support was merged upstream. Hooray. This repository will now disappear."

:stuck_out_tongue_closed_eyes:

**Comment by dlenski** [comment]
If you want detailed development updates… follow the `openconnect-devel` mailing list.

From the user perspective, the only meaningful update ever is going to be "Support was merged upstream. Hooray. This repository will now disappear."

:stuck_out_tongue_closed_eyes:

**Comment by dlenski** [comment]
GlobalProtect support [has been merged into the upstream `master`](http://git.infradead.org/users/dwmw2/openconnect.git/shortlog/) and [it will be released in openconnect 8.0](http://lists.infradead.org/pipermail/openconnect-devel/2018-May/004866.html).

:beer: :beers: :beer: :beers: :beer: :beers:

**Comment by candrews** [comment]
Has the NetworkManager project been notified about this new openconnect functionality? I bet they'll be quite interested :)
